import type { Floorplan } from "@/lib/insome/floorplan";
import { homeFloorplanVariants } from "./floorplan-variants.home";
import type { DesignerLevel } from "./designer-levels";
import type { WorkCategory, WorkStyleFilter } from "./work-categories";

export interface WorkCreator {
  readonly id: string;
  readonly name: string;
  readonly level: DesignerLevel;
  readonly isVerified: boolean;
  readonly isHomeowner: boolean;
}

export interface Work {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly thumbnail?: string | undefined;
  readonly category: Exclude<WorkCategory, "all">;
  readonly style: Exclude<WorkStyleFilter, "all">;
  readonly coverAccent: "warm" | "cool" | "neutral";
  readonly aspectRatio: "portrait" | "landscape" | "square" | "tall";
  readonly tags: ReadonlyArray<string>;
  readonly creator: WorkCreator;
  readonly totalAreaSqm: number;
  readonly stories: 1 | 2 | 3 | 4;
  readonly bedrooms: number;
  readonly bathrooms: number;
  readonly estimatedPriceMinWan: number;
  readonly estimatedPriceMaxWan: number;
  readonly constructionDays: number;
  readonly savingsPercent: number;
  readonly likes: number;
  readonly views: number;
  readonly adoptedCount: number;
  readonly publishedAt: string;
  readonly floorplan?: Floorplan | undefined;
}

/**
 * Phase 4.0.12 — 30 works imported from `.reference/landing-source/galleryData`,
 * INSOME-recontextualized. First 3 are wired to real Home variants so the
 * "我要同款 → /home/design/[id]" flow lands on an editable floorplan. The
 * rest are display-only cards.
 *
 * Schema simplified to literal strings (name/description/tags) — works are
 * user-generated content and don't need i18n abstraction.
 *
 * TODO(phase-4.1): replace with GET /api/works (Supabase).
 */
const unsplashPhoto = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;

const workThumbnailAssets = [
  unsplashPhoto("photo-1600585154340-be6161a56a0c"),
  unsplashPhoto("photo-1518780664697-55e3ad937233"),
  unsplashPhoto("photo-1600607687939-ce8a6c25118c"),
  unsplashPhoto("photo-1523413651479-597eb2da0ad6"),
  unsplashPhoto("photo-1600210492486-724fe5c67fb0"),
  unsplashPhoto("photo-1510798831971-661eb04b3739"),
  unsplashPhoto("photo-1600585154526-990dced4db0d"),
  unsplashPhoto("photo-1497366754035-f200968a6e72"),
  unsplashPhoto("photo-1518005020951-eccb494ad742"),
  unsplashPhoto("photo-1523217582562-09d0def993a6"),
  unsplashPhoto("photo-1480074568708-e7b720bb3f09"),
  unsplashPhoto("photo-1556912167-f556f1f39fdf"),
  unsplashPhoto("photo-1500534314209-a25ddb2bd429"),
  unsplashPhoto("photo-1616594039964-ae9021a400a0"),
  unsplashPhoto("photo-1571896349842-33c89424de2d"),
  unsplashPhoto("photo-1600607687920-4e2a09cf159d"),
  unsplashPhoto("photo-1507525428034-b723cf961d3e"),
  unsplashPhoto("photo-1560448204-e02f11c3d0e2"),
  unsplashPhoto("photo-1517248135467-4c7edcad34c4"),
  unsplashPhoto("photo-1570129477492-45c003edd2be"),
  unsplashPhoto("photo-1554118811-1e0d58224f24"),
  unsplashPhoto("photo-1560448075-bb485b067938"),
  unsplashPhoto("photo-1499793983690-e29da59ef1c2"),
  unsplashPhoto("photo-1528164344705-47542687000d"),
  unsplashPhoto("photo-1504851149312-7a075b496cc7"),
  unsplashPhoto("photo-1497366811353-6870744d04b2"),
  unsplashPhoto("photo-1542314831-068cd1dbfeeb"),
  unsplashPhoto("photo-1506905925346-21bda4d32df4"),
  unsplashPhoto("photo-1512917774080-9991f1c4c750"),
  unsplashPhoto("photo-1615874959474-d609969a20ed"),
] as const;

const workThumbnail = (index: number) => workThumbnailAssets[index % workThumbnailAssets.length];

export const mockWorks: ReadonlyArray<Work> = [
  {
    id: "w-001",
    name: "现代极简别墅",
    description: "位于海边的现代极简风格别墅，融合自然光线与极简美学，打造宁静的居住空间。装配式重钢结构，30 天交付，节省 25% 成本。",
    thumbnail: workThumbnail(0),
    category: "architecture",
    style: "modern",
    coverAccent: "cool",
    aspectRatio: "portrait",
    tags: ["别墅", "海景", "大平层"],
    creator: { id: "u-alex", name: "Alex Chen", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 480,
    stories: 3,
    bedrooms: 5,
    bathrooms: 4,
    estimatedPriceMinWan: 720,
    estimatedPriceMaxWan: 850,
    constructionDays: 75,
    savingsPercent: 25,
    likes: 2847,
    views: 15632,
    adoptedCount: 38,
    publishedAt: "2024-03-15",
    floorplan: homeFloorplanVariants[0],
  },
  {
    id: "w-002",
    name: "森林中的玻璃屋",
    description: "隐藏在森林深处的全玻璃结构住宅，与自然环境完美融合。重钢框架 + 大面积玻璃幕墙，模块化预制。",
    thumbnail: workThumbnail(1),
    category: "architecture",
    style: "modern",
    coverAccent: "neutral",
    aspectRatio: "tall",
    tags: ["玻璃屋", "木结构", "自然采光"],
    creator: { id: "u-maya", name: "Maya Lin", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 320,
    stories: 2,
    bedrooms: 3,
    bathrooms: 3,
    estimatedPriceMinWan: 980,
    estimatedPriceMaxWan: 1200,
    constructionDays: 60,
    savingsPercent: 24,
    likes: 3621,
    views: 21340,
    adoptedCount: 52,
    publishedAt: "2024-03-12",
    floorplan: homeFloorplanVariants[1],
  },
  {
    id: "w-003",
    name: "MUSE M+S",
    description: "城市中心的垂直绿化建筑，将自然引入高密度都市空间。立面绿植与重钢结构结合，碳排减半。",
    thumbnail: workThumbnail(2),
    category: "architecture",
    style: "modern",
    coverAccent: "neutral",
    aspectRatio: "tall",
    tags: ["绿化", "绿色幕墙", "低碳"],
    creator: { id: "u-john", name: "John Wang", level: 3, isVerified: true, isHomeowner: false },
    totalAreaSqm: 135,
    stories: 4,
    bedrooms: 3,
    bathrooms: 2,
    estimatedPriceMinWan: 95,
    estimatedPriceMaxWan: 130,
    constructionDays: 50,
    savingsPercent: 28,
    likes: 1956,
    views: 12890,
    adoptedCount: 22,
    publishedAt: "2024-03-08",
    floorplan: homeFloorplanVariants[2],
  },
  {
    id: "w-004",
    name: "禅意茶室",
    description: "日式禅意茶室设计，追求极致的宁静与侘寂之美。轻钢结构 + 木格栅，30 天交付。",
    thumbnail: workThumbnail(3),
    category: "interior",
    style: "minimalist",
    coverAccent: "neutral",
    aspectRatio: "square",
    tags: ["茶室", "日式", "侘寂"],
    creator: { id: "u-li", name: "Li Wei", level: 2, isVerified: false, isHomeowner: false },
    totalAreaSqm: 85,
    stories: 1,
    bedrooms: 1,
    bathrooms: 1,
    estimatedPriceMinWan: 140,
    estimatedPriceMaxWan: 180,
    constructionDays: 30,
    savingsPercent: 30,
    likes: 4213,
    views: 28450,
    adoptedCount: 76,
    publishedAt: "2024-03-08",
  },
  {
    id: "w-005",
    name: "极简客厅",
    description: "黑白灰为主调的极简客厅，大面积落地窗引入充足采光。装配式标准户型，35 天完工。",
    thumbnail: workThumbnail(4),
    category: "interior",
    style: "minimalist",
    coverAccent: "neutral",
    aspectRatio: "landscape",
    tags: ["黑白灰", "落地窗", "北欧"],
    creator: { id: "u-sarah", name: "Sarah Kim", level: 3, isVerified: true, isHomeowner: false },
    totalAreaSqm: 120,
    stories: 1,
    bedrooms: 3,
    bathrooms: 1,
    estimatedPriceMinWan: 35,
    estimatedPriceMaxWan: 45,
    constructionDays: 35,
    savingsPercent: 27,
    likes: 3156,
    views: 19230,
    adoptedCount: 31,
    publishedAt: "2024-03-05",
  },
  {
    id: "w-006",
    name: "北欧小木屋",
    description: "北欧风格的木质住宅，原木与白雪的自然对话。胶合木 + 钢节点装配式结构。",
    thumbnail: workThumbnail(5),
    category: "architecture",
    style: "scandinavian",
    coverAccent: "warm",
    aspectRatio: "portrait",
    tags: ["木结构", "别墅", "雪景"],
    creator: { id: "u-erik", name: "Erik Nord", level: 3, isVerified: true, isHomeowner: false },
    totalAreaSqm: 210,
    stories: 2,
    bedrooms: 4,
    bathrooms: 3,
    estimatedPriceMinWan: 320,
    estimatedPriceMaxWan: 380,
    constructionDays: 50,
    savingsPercent: 26,
    likes: 2874,
    views: 17650,
    adoptedCount: 41,
    publishedAt: "2024-03-03",
  },
  {
    id: "w-007",
    name: "日式枯山水庭院",
    description: "精心设计的枯山水庭院，白砂与青苔的禅意组合。配套轻钢茶室单体。",
    thumbnail: workThumbnail(6),
    category: "architecture",
    style: "minimalist",
    coverAccent: "neutral",
    aspectRatio: "square",
    tags: ["枯山水", "青苔", "禅意"],
    creator: { id: "u-tanaka", name: "Tanaka Yuki", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 180,
    stories: 1,
    bedrooms: 2,
    bathrooms: 2,
    estimatedPriceMinWan: 95,
    estimatedPriceMaxWan: 120,
    constructionDays: 42,
    savingsPercent: 28,
    likes: 5532,
    views: 32100,
    adoptedCount: 78,
    publishedAt: "2024-03-01",
  },
  {
    id: "w-008",
    name: "科技感书房",
    description: "赛博朋克风格的书房设计，RGB 灯光与金属质感结合。轻钢结构改造，模块化预留线槽。",
    thumbnail: workThumbnail(7),
    category: "interior",
    style: "industrial",
    coverAccent: "cool",
    aspectRatio: "landscape",
    tags: ["赛博朋克", "RGB灯", "金属"],
    creator: { id: "u-mike", name: "Mike Zhang", level: 2, isVerified: false, isHomeowner: false },
    totalAreaSqm: 45,
    stories: 1,
    bedrooms: 0,
    bathrooms: 0,
    estimatedPriceMinWan: 50,
    estimatedPriceMaxWan: 65,
    constructionDays: 25,
    savingsPercent: 32,
    likes: 2134,
    views: 14560,
    adoptedCount: 18,
    publishedAt: "2024-02-28",
  },
  {
    id: "w-009",
    name: "COCANO SHOP",
    description: "未来都市概念零售空间，钢柱玻璃幕墙 + 流线型曲面设计。商业装配式典范。",
    thumbnail: workThumbnail(8),
    category: "architecture",
    style: "modern",
    coverAccent: "cool",
    aspectRatio: "portrait",
    tags: ["商业", "空间", "零售"],
    creator: { id: "u-neo", name: "Neo Wang", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 220,
    stories: 1,
    bedrooms: 0,
    bathrooms: 1,
    estimatedPriceMinWan: 165,
    estimatedPriceMaxWan: 210,
    constructionDays: 38,
    savingsPercent: 26,
    likes: 6789,
    views: 45200,
    adoptedCount: 44,
    publishedAt: "2024-02-25",
  },
  {
    id: "w-010",
    name: "MUSE M",
    description: "传统中式园林的现代演绎，亭台楼阁与水系环绕。新中式装配式建筑。",
    thumbnail: workThumbnail(9),
    category: "architecture",
    style: "classic",
    coverAccent: "neutral",
    aspectRatio: "landscape",
    tags: ["森林", "水系", "现代"],
    creator: { id: "u-chen", name: "Chen Ming", level: 3, isVerified: false, isHomeowner: false },
    totalAreaSqm: 67,
    stories: 1,
    bedrooms: 1,
    bathrooms: 1,
    estimatedPriceMinWan: 22,
    estimatedPriceMaxWan: 30,
    constructionDays: 28,
    savingsPercent: 30,
    likes: 4890,
    views: 31200,
    adoptedCount: 54,
    publishedAt: "2024-02-22",
  },
  {
    id: "w-011",
    name: "竹木居",
    description: "竹木结构的现代中式住宅，自然材质的禅意空间。胶合木 + 钢节点连接，全装配式。",
    thumbnail: workThumbnail(10),
    category: "interior",
    style: "scandinavian",
    coverAccent: "warm",
    aspectRatio: "portrait",
    tags: ["竹木", "自然", "禅意"],
    creator: { id: "u-d5a", name: "D5 Studio", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 51,
    stories: 1,
    bedrooms: 1,
    bathrooms: 1,
    estimatedPriceMinWan: 130,
    estimatedPriceMaxWan: 180,
    constructionDays: 35,
    savingsPercent: 28,
    likes: 6234,
    views: 38400,
    adoptedCount: 56,
    publishedAt: "2024-03-15",
  },
  {
    id: "w-012",
    name: "极简厨房",
    description: "开放式极简厨房，中岛台设计，大理石与原木的碰撞。预制中岛模块快速安装。",
    thumbnail: workThumbnail(11),
    category: "interior",
    style: "modern",
    coverAccent: "neutral",
    aspectRatio: "landscape",
    tags: ["中岛台", "大理石", "原木"],
    creator: { id: "u-emma", name: "Emma Liu", level: 2, isVerified: false, isHomeowner: false },
    totalAreaSqm: 35,
    stories: 1,
    bedrooms: 0,
    bathrooms: 0,
    estimatedPriceMinWan: 28,
    estimatedPriceMaxWan: 38,
    constructionDays: 22,
    savingsPercent: 30,
    likes: 2567,
    views: 16890,
    adoptedCount: 28,
    publishedAt: "2024-02-18",
  },
  {
    id: "w-013",
    name: "山地度假屋",
    description: "隐匿于山间的现代度假屋，享有绝佳的山景视野。钢柱悬挑结构，模块化预制。",
    thumbnail: workThumbnail(12),
    category: "architecture",
    style: "modern",
    coverAccent: "warm",
    aspectRatio: "tall",
    tags: ["山景", "度假", "别墅"],
    creator: { id: "u-jack", name: "Jack Ma", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 280,
    stories: 2,
    bedrooms: 4,
    bathrooms: 3,
    estimatedPriceMinWan: 540,
    estimatedPriceMaxWan: 680,
    constructionDays: 60,
    savingsPercent: 25,
    likes: 3456,
    views: 21400,
    adoptedCount: 33,
    publishedAt: "2024-02-15",
  },
  {
    id: "w-014",
    name: "梦幻星空卧室",
    description: "梦幻般的卧室设计，星空天花板与柔和灯光营造浪漫氛围。预制独立单元。",
    thumbnail: workThumbnail(13),
    category: "interior",
    style: "scandinavian",
    coverAccent: "cool",
    aspectRatio: "square",
    tags: ["星空", "柔光", "浪漫"],
    creator: { id: "u-dream", name: "Dream Studio", level: 3, isVerified: true, isHomeowner: false },
    totalAreaSqm: 25,
    stories: 1,
    bedrooms: 1,
    bathrooms: 0,
    estimatedPriceMinWan: 18,
    estimatedPriceMaxWan: 28,
    constructionDays: 18,
    savingsPercent: 33,
    likes: 6123,
    views: 38900,
    adoptedCount: 71,
    publishedAt: "2024-02-12",
  },
  {
    id: "w-015",
    name: "热带雨林别墅",
    description: "置身于热带雨林中的豪华别墅，室内外空间的完美融合。钢结构耐腐蚀防潮。",
    thumbnail: workThumbnail(14),
    category: "architecture",
    style: "modern",
    coverAccent: "warm",
    aspectRatio: "landscape",
    tags: ["热带", "泳池", "雨林"],
    creator: { id: "u-paradise", name: "Paradise Arc", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 650,
    stories: 2,
    bedrooms: 5,
    bathrooms: 4,
    estimatedPriceMinWan: 1200,
    estimatedPriceMaxWan: 1500,
    constructionDays: 70,
    savingsPercent: 23,
    likes: 4567,
    views: 28700,
    adoptedCount: 25,
    publishedAt: "2024-02-10",
  },
  {
    id: "w-016",
    name: "Micron 公寓",
    description: "极简主义现代美术馆，纯粹的几何体量与光影交织。装配式幕墙系统。",
    thumbnail: workThumbnail(15),
    category: "architecture",
    style: "minimalist",
    coverAccent: "neutral",
    aspectRatio: "tall",
    tags: ["几何", "光影", "极简"],
    creator: { id: "u-art", name: "Art Arc", level: 3, isVerified: true, isHomeowner: false },
    totalAreaSqm: 217,
    stories: 2,
    bedrooms: 3,
    bathrooms: 2,
    estimatedPriceMinWan: 60,
    estimatedPriceMaxWan: 80,
    constructionDays: 45,
    savingsPercent: 27,
    likes: 3456,
    views: 21340,
    adoptedCount: 28,
    publishedAt: "2024-02-05",
  },
  {
    id: "w-017",
    name: "热带海滨别墅",
    description: "面朝大海的热带海滨别墅，阳光与海浪的诗意栖居。钢结构 + 防腐蚀涂层。",
    thumbnail: workThumbnail(16),
    category: "architecture",
    style: "modern",
    coverAccent: "cool",
    aspectRatio: "landscape",
    tags: ["海滨", "别墅", "阳光"],
    creator: { id: "u-coast", name: "Coast Living", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 380,
    stories: 2,
    bedrooms: 5,
    bathrooms: 4,
    estimatedPriceMinWan: 1800,
    estimatedPriceMaxWan: 2200,
    constructionDays: 65,
    savingsPercent: 23,
    likes: 5678,
    views: 34200,
    adoptedCount: 38,
    publishedAt: "2024-02-03",
  },
  {
    id: "w-018",
    name: "智能家居客厅",
    description: "全屋智能控制的现代客厅，科技与生活的完美融合。模块化预留智能线槽。",
    thumbnail: workThumbnail(17),
    category: "interior",
    style: "modern",
    coverAccent: "cool",
    aspectRatio: "landscape",
    tags: ["全屋智能", "科技", "极简"],
    creator: { id: "u-tech", name: "Tech Home", level: 3, isVerified: true, isHomeowner: false },
    totalAreaSqm: 65,
    stories: 1,
    bedrooms: 0,
    bathrooms: 0,
    estimatedPriceMinWan: 95,
    estimatedPriceMaxWan: 120,
    constructionDays: 28,
    savingsPercent: 30,
    likes: 4321,
    views: 26890,
    adoptedCount: 35,
    publishedAt: "2024-01-30",
  },
  {
    id: "w-019",
    name: "和风餐厅",
    description: "传统与现代融合的日式餐厅，匠心独运的用餐空间。商业装配式标准。",
    thumbnail: workThumbnail(18),
    category: "interior",
    style: "classic",
    coverAccent: "warm",
    aspectRatio: "landscape",
    tags: ["日式", "餐饮", "和风"],
    creator: { id: "u-tokyo", name: "Tokyo Taste", level: 3, isVerified: true, isHomeowner: false },
    totalAreaSqm: 220,
    stories: 1,
    bedrooms: 0,
    bathrooms: 2,
    estimatedPriceMinWan: 320,
    estimatedPriceMaxWan: 380,
    constructionDays: 42,
    savingsPercent: 26,
    likes: 4567,
    views: 28900,
    adoptedCount: 30,
    publishedAt: "2024-01-20",
  },
  {
    id: "w-020",
    name: "英式花园别墅",
    description: "经典的英式乡村别墅，优雅与传统的完美诠释。胶合木 + 钢节点典藏装配。",
    thumbnail: workThumbnail(19),
    category: "architecture",
    style: "classic",
    coverAccent: "warm",
    aspectRatio: "tall",
    tags: ["别墅", "英式", "花园"],
    creator: { id: "u-manor", name: "English Manor", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 680,
    stories: 3,
    bedrooms: 6,
    bathrooms: 5,
    estimatedPriceMinWan: 2800,
    estimatedPriceMaxWan: 3500,
    constructionDays: 75,
    savingsPercent: 22,
    likes: 5678,
    views: 35600,
    adoptedCount: 28,
    publishedAt: "2024-01-15",
  },
  {
    id: "w-021",
    name: "工业风咖啡馆",
    description: "复古工业风格咖啡馆，金属与木质的碰撞美学。轻钢结构改造工程。",
    thumbnail: workThumbnail(20),
    category: "interior",
    style: "industrial",
    coverAccent: "warm",
    aspectRatio: "landscape",
    tags: ["工业风", "咖啡", "复古"],
    creator: { id: "u-bean", name: "Bean House", level: 2, isVerified: false, isHomeowner: false },
    totalAreaSqm: 180,
    stories: 1,
    bedrooms: 0,
    bathrooms: 1,
    estimatedPriceMinWan: 65,
    estimatedPriceMaxWan: 85,
    constructionDays: 32,
    savingsPercent: 30,
    likes: 3456,
    views: 22400,
    adoptedCount: 25,
    publishedAt: "2024-01-12",
  },
  {
    id: "w-022",
    name: "极简北欧公寓",
    description: "温暖的北欧风格公寓，极简与舒适的完美平衡。装配式标准户型。",
    thumbnail: workThumbnail(21),
    category: "interior",
    style: "scandinavian",
    coverAccent: "warm",
    aspectRatio: "portrait",
    tags: ["北欧", "温暖", "极简"],
    creator: { id: "u-nordic", name: "Nordic Living", level: 3, isVerified: false, isHomeowner: false },
    totalAreaSqm: 85,
    stories: 1,
    bedrooms: 2,
    bathrooms: 1,
    estimatedPriceMinWan: 75,
    estimatedPriceMaxWan: 95,
    constructionDays: 30,
    savingsPercent: 28,
    likes: 4321,
    views: 27600,
    adoptedCount: 32,
    publishedAt: "2024-01-08",
  },
  {
    id: "w-023",
    name: "水上漂浮别墅",
    description: "湖面上的现代漂浮别墅，水天一色的诗意栖居。钢浮箱基础 + 装配式上部结构。",
    thumbnail: workThumbnail(22),
    category: "architecture",
    style: "modern",
    coverAccent: "cool",
    aspectRatio: "tall",
    tags: ["漂浮", "湖景", "别墅"],
    creator: { id: "u-aqua", name: "Aqua Living", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 280,
    stories: 2,
    bedrooms: 4,
    bathrooms: 3,
    estimatedPriceMinWan: 1500,
    estimatedPriceMaxWan: 1800,
    constructionDays: 65,
    savingsPercent: 22,
    likes: 7890,
    views: 48700,
    adoptedCount: 32,
    publishedAt: "2024-01-05",
  },
  {
    id: "w-024",
    name: "板麦民宿",
    description: "依山而建的日式温泉旅馆，自然与传统的完美融合。山地装配式快速建造。",
    thumbnail: workThumbnail(23),
    category: "architecture",
    style: "scandinavian",
    coverAccent: "warm",
    aspectRatio: "square",
    tags: ["田园", "日式", "山景"],
    creator: { id: "u-onsen", name: "Onsen Stay", level: 3, isVerified: true, isHomeowner: false },
    totalAreaSqm: 42,
    stories: 1,
    bedrooms: 1,
    bathrooms: 1,
    estimatedPriceMinWan: 14,
    estimatedPriceMaxWan: 19,
    constructionDays: 25,
    savingsPercent: 32,
    likes: 8765,
    views: 54300,
    adoptedCount: 84,
    publishedAt: "2024-01-02",
  },
  {
    id: "w-025",
    name: "海南营地",
    description: "树屋酒店，与自然零距离的栖息体验。轻钢悬挑 + 木装饰一体化预制。",
    thumbnail: workThumbnail(24),
    category: "architecture",
    style: "modern",
    coverAccent: "warm",
    aspectRatio: "portrait",
    tags: ["生态", "森林", "树屋"],
    creator: { id: "u-tree", name: "Tree House Stay", level: 3, isVerified: true, isHomeowner: false },
    totalAreaSqm: 77,
    stories: 1,
    bedrooms: 1,
    bathrooms: 1,
    estimatedPriceMinWan: 25,
    estimatedPriceMaxWan: 35,
    constructionDays: 28,
    savingsPercent: 33,
    likes: 9876,
    views: 61200,
    adoptedCount: 92,
    publishedAt: "2023-12-28",
  },
  {
    id: "w-026",
    name: "极简办公空间",
    description: "开放式极简办公空间，激发创造力的工作环境。商业建筑装配式典范。",
    thumbnail: workThumbnail(25),
    category: "interior",
    style: "modern",
    coverAccent: "neutral",
    aspectRatio: "landscape",
    tags: ["开放式", "极简", "绿植"],
    creator: { id: "u-office", name: "Office Design", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 1200,
    stories: 1,
    bedrooms: 0,
    bathrooms: 4,
    estimatedPriceMinWan: 380,
    estimatedPriceMaxWan: 500,
    constructionDays: 55,
    savingsPercent: 28,
    likes: 4321,
    views: 28700,
    adoptedCount: 18,
    publishedAt: "2023-12-20",
  },
  {
    id: "w-027",
    name: "ZEN BOX",
    description: "巴厘岛风格度假别墅，文明与自然的和谐共生。模块化集装箱式快速装配。",
    thumbnail: workThumbnail(26),
    category: "architecture",
    style: "scandinavian",
    coverAccent: "warm",
    aspectRatio: "square",
    tags: ["金属", "木", "自然"],
    creator: { id: "u-bali", name: "Bali Retreat", level: 3, isVerified: false, isHomeowner: false },
    totalAreaSqm: 31,
    stories: 1,
    bedrooms: 1,
    bathrooms: 1,
    estimatedPriceMinWan: 11,
    estimatedPriceMaxWan: 15,
    constructionDays: 20,
    savingsPercent: 33,
    likes: 7890,
    views: 48700,
    adoptedCount: 88,
    publishedAt: "2023-12-15",
  },
  {
    id: "w-028",
    name: "瑞士阿尔卑斯山小屋",
    description: "瑞士阿尔卑斯山传统木屋，滑雪季的温馨归宿。胶合木 + 钢节点深山速建。",
    thumbnail: workThumbnail(27),
    category: "architecture",
    style: "scandinavian",
    coverAccent: "warm",
    aspectRatio: "portrait",
    tags: ["木屋", "雪山", "滑雪"],
    creator: { id: "u-alpine", name: "Alpine Lodge", level: 3, isVerified: true, isHomeowner: false },
    totalAreaSqm: 180,
    stories: 2,
    bedrooms: 3,
    bathrooms: 2,
    estimatedPriceMinWan: 950,
    estimatedPriceMaxWan: 1200,
    constructionDays: 55,
    savingsPercent: 24,
    likes: 8765,
    views: 54300,
    adoptedCount: 30,
    publishedAt: "2023-11-28",
  },
  {
    id: "w-029",
    name: "山涧民宿",
    description: "隐匿于山涧溪流旁的民宿建筑，与自然和谐共生的栖居体验。装配式山地住宅。",
    thumbnail: workThumbnail(28),
    category: "architecture",
    style: "scandinavian",
    coverAccent: "warm",
    aspectRatio: "landscape",
    tags: ["民宿", "山水", "自然"],
    creator: { id: "u-d5b", name: "D5 Studio", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 280,
    stories: 2,
    bedrooms: 4,
    bathrooms: 3,
    estimatedPriceMinWan: 380,
    estimatedPriceMaxWan: 480,
    constructionDays: 50,
    savingsPercent: 26,
    likes: 5678,
    views: 32400,
    adoptedCount: 42,
    publishedAt: "2024-06-05",
  },
  {
    id: "w-030",
    name: "栖桐居·宁",
    description: "宁静雅致的新中式室内空间，梧桐树下的诗意栖居。新中式装配式典范。",
    thumbnail: workThumbnail(29),
    category: "interior",
    style: "classic",
    coverAccent: "warm",
    aspectRatio: "portrait",
    tags: ["新中式", "雅致", "宁静"],
    creator: { id: "u-d5c", name: "D5 Studio", level: 4, isVerified: true, isHomeowner: false },
    totalAreaSqm: 220,
    stories: 2,
    bedrooms: 4,
    bathrooms: 3,
    estimatedPriceMinWan: 480,
    estimatedPriceMaxWan: 580,
    constructionDays: 55,
    savingsPercent: 25,
    likes: 5432,
    views: 31500,
    adoptedCount: 38,
    publishedAt: "2024-05-28",
  },
];

export function getWorkById(id: string): Work | undefined {
  return mockWorks.find((w) => w.id === id);
}
