export const assetKinds = [
  "ifc",
  "cad",
  "pdf",
  "office",
  "image",
  "video",
  "audio",
  "point_cloud",
  "panorama",
  "gis_layer",
  "gantt",
  "flow_diagram",
  "model_3d",
  "unknown",
] as const;

export const conversionOperations = [
  "ifc_ingest",
  "ifc_to_glb",
  "ifc_to_3dtiles",
  "cad_convert",
  "cad_extract_entities",
  "pdf_parse",
  "ocr",
  "office_convert",
  "gis_tile",
  "pointcloud_tile",
  "panorama_ingest",
  "media_transcode",
  "gantt_generate",
  "flow_generate",
] as const;

export const viewerCommandKinds = [
  "select_objects",
  "isolate_objects",
  "hide_objects",
  "show_objects",
  "set_color",
  "set_alpha",
  "zoom_to",
  "section_plane",
  "measure_distance",
  "measure_area",
  "create_annotation",
  "link_drawing_to_model",
  "load_gis_layer",
  "load_3d_tiles",
  "load_panorama",
  "sync_panorama_camera",
] as const;

export const runtimeStack = {
  frontend: [
    "Vite 8",
    "React 19",
    "TanStack Router",
    "TanStack Query",
    "Zustand",
    "Tailwind CSS",
    "Radix UI",
    "React Three Fiber",
    "Three.js WebGPU",
    "CesiumJS",
    "MapLibre GL JS",
    "3d-tiles-renderer",
  ],
  backend: [
    "Rust",
    "Axum",
    "Tokio",
    "SeaORM",
    "PostgreSQL",
    "PostGIS",
    "pgvector",
    "PGMQ",
    "SeaweedFS S3",
    "Temporal",
    "Meilisearch",
    "OpenTelemetry",
    "Langfuse",
  ],
  protectedBoundaries: [
    "RuntimeContext",
    "RBAC",
    "tenant/project isolation",
    "audit events",
    "OpenAPI contract",
    "license/security CI",
    "production profile strict context",
    "no proprietary wasm/exe/loader in core",
  ],
} as const;
