#!/usr/bin/env python3
"""Local production smoke fixture for S3-compatible storage and TextToBim."""

from __future__ import annotations

import argparse
import hashlib
import json
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import ClassVar


IFC_BYTES = b"""ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('ArchIToken production smoke IFC fixture'),'2;1');
FILE_NAME('architoken-production-smoke.ifc','2026-05-16T00:00:00',('ArchIToken'),('ArchIToken'),'ArchIToken','ArchIToken','');
FILE_SCHEMA(('IFC4X3_ADD2'));
ENDSEC;
DATA;
#1=IFCPROJECT('0V5wYb1W9D_xSmoke000001',$,'ArchIToken Production Smoke',$,$,$,$,$,$);
ENDSEC;
END-ISO-10303-21;
"""


class FixtureHandler(BaseHTTPRequestHandler):
    server_version = "ArchITokenProductionSmoke/1.0"
    objects: ClassVar[dict[str, tuple[bytes, str]]] = {}
    public_base_url: ClassVar[str] = "http://127.0.0.1:19081"

    def log_message(self, fmt: str, *args: object) -> None:
        return

    def do_GET(self) -> None:  # noqa: N802
        if self.path == "/healthz":
            self.send_json(200, {"status": "ok"})
            return
        if self.path == "/download/architoken-production-smoke.ifc":
            self.send_bytes(200, IFC_BYTES, "model/ifc", etag=sha256(IFC_BYTES))
            return
        if self.path in self.objects:
            body, content_type = self.objects[self.path]
            self.send_bytes(200, body, content_type, etag=sha256(body))
            return
        self.send_json(404, {"error": "not found"})

    def do_HEAD(self) -> None:  # noqa: N802
        if self.path in self.objects:
            body, content_type = self.objects[self.path]
            self.send_response(200)
            self.send_header("content-type", content_type)
            self.send_header("content-length", str(len(body)))
            self.send_header("etag", sha256(body))
            self.end_headers()
            return
        self.send_response(404)
        self.end_headers()

    def do_PUT(self) -> None:  # noqa: N802
        body = self.read_body()
        content_type = self.headers.get("content-type", "application/octet-stream")
        self.objects[self.path] = (body, content_type)
        self.send_response(200)
        self.send_header("etag", sha256(body))
        self.send_header("content-length", "0")
        self.end_headers()

    def do_POST(self) -> None:  # noqa: N802
        if self.path != "/v1/generate/text-to-bim":
            self.send_json(404, {"error": "not found"})
            return
        _ = self.read_body()
        digest = sha256(IFC_BYTES)
        self.send_json(
            200,
            {
                "engine": "architoken-production-smoke-fixture",
                "model": "ifc4x3-contract-fixture",
                "summary": "IFC4x3 BIM artifact generated by the local production smoke fixture.",
                "modelCalls": 1,
                "artifacts": [
                    {
                        "kind": "bim",
                        "geometryFormat": "ifc",
                        "mimeType": "model/ifc",
                        "filename": "architoken-production-smoke.ifc",
                        "downloadUrl": f"{self.public_base_url}/download/architoken-production-smoke.ifc",
                        "objectUri": None,
                        "sizeBytes": len(IFC_BYTES),
                        "checksum": digest,
                        "schemaRef": "IFC4X3_ADD2",
                        "viewerAdapterHint": "threejs-ifc",
                    }
                ],
            },
        )

    def read_body(self) -> bytes:
        length = int(self.headers.get("content-length", "0"))
        return self.rfile.read(length) if length else b""

    def send_json(self, status: int, payload: dict[str, object]) -> None:
        body = json.dumps(payload, separators=(",", ":")).encode()
        self.send_response(status)
        self.send_header("content-type", "application/json")
        self.send_header("content-length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def send_bytes(
        self, status: int, body: bytes, content_type: str, *, etag: str
    ) -> None:
        self.send_response(status)
        self.send_header("content-type", content_type)
        self.send_header("content-length", str(len(body)))
        self.send_header("etag", etag)
        self.end_headers()
        self.wfile.write(body)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=19081)
    parser.add_argument("--public-base-url")
    args = parser.parse_args()

    FixtureHandler.public_base_url = (
        args.public_base_url or f"http://{args.host}:{args.port}"
    )
    server = ThreadingHTTPServer((args.host, args.port), FixtureHandler)
    server.serve_forever()


if __name__ == "__main__":
    main()
