#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

export ARCHITOKEN_DB_MANAGER_ADDR="${ARCHITOKEN_DB_MANAGER_ADDR:-127.0.0.1:8751}"
export ARCHITOKEN_DB_MANAGER_POSTGRES_URL="${ARCHITOKEN_DB_MANAGER_POSTGRES_URL:-postgres://architoken:architoken_dev_only@127.0.0.1:5433/architoken}"
export ARCHITOKEN_GRAPH__URL="${ARCHITOKEN_GRAPH__URL:-http://127.0.0.1:8088}"

export ARCHITOKEN_DB_MANAGER_CLICKHOUSE_URL="${ARCHITOKEN_DB_MANAGER_CLICKHOUSE_URL:-http://127.0.0.1:8123}"
export CLICKHOUSE_USER="${CLICKHOUSE_USER:-architoken}"
export CLICKHOUSE_PASSWORD="${CLICKHOUSE_PASSWORD:-architoken_dev_only}"

export ARCHITOKEN_DB_MANAGER_VALKEY_URL="${ARCHITOKEN_DB_MANAGER_VALKEY_URL:-redis://127.0.0.1:6381/0}"
export ARCHITOKEN_DB_MANAGER_QDRANT_URL="${ARCHITOKEN_DB_MANAGER_QDRANT_URL:-http://127.0.0.1:6333}"
export ARCHITOKEN_DB_MANAGER_NATS_MONITOR_URL="${ARCHITOKEN_DB_MANAGER_NATS_MONITOR_URL:-http://127.0.0.1:8222}"

export ARCHITOKEN_DB_MANAGER_S3_ENDPOINT="${ARCHITOKEN_DB_MANAGER_S3_ENDPOINT:-http://127.0.0.1:8333}"
export ARCHITOKEN_DB_MANAGER_S3_BUCKET="${ARCHITOKEN_DB_MANAGER_S3_BUCKET:-architoken-assets}"

cd "${REPO_ROOT}"
exec 04-backend/target/debug/architoken-db-manager
