// lib/adapter-source-registry.ts - Upstream adapter and format routing registry
// License: Apache-2.0

export type AdapterSourceDecision =
  | 'selected'
  | 'selected_external_process'
  | 'licensed_gated'
  | 'reference_only'
  | 'sample_data'
  | 'blocked_pending_license';

export type AdapterCapability =
  | 'import'
  | 'export'
  | 'online_edit'
  | 'ai_generate'
  | 'validate'
  | 'sync'
  | 'automation'
  | 'viewer'
  | 'ocr'
  | 'document_conversion';

export type AdapterSourceCategory =
  | 'standards'
  | 'openbim'
  | 'cad'
  | 'bim_authoring'
  | 'document'
  | 'erp'
  | 'sync'
  | 'ai_generation'
  | 'mcp'
  | 'sample_data'
  | 'visualization';

export type AdapterSourceState =
  | 'active'
  | 'archived'
  | 'organization'
  | 'external';

export interface AdapterSource {
  id: string;
  url: string;
  label: string;
  category: AdapterSourceCategory;
  decision: AdapterSourceDecision;
  state: AdapterSourceState;
  license: string | null;
  formats: readonly string[];
  capabilities: readonly AdapterCapability[];
  note: string;
}

export interface FormatAdapterRequirement {
  family: string;
  extensions: readonly string[];
  adapters: readonly string[];
  sourceIds: readonly string[];
  importRoute: 'direct_browser' | 'worker' | 'service' | 'licensed_service';
  onlineEditRoute: 'native' | 'worker' | 'service' | 'licensed_service';
  aiGenerationRoute: 'worker' | 'provider' | 'licensed_service';
  exportRoute: 'direct' | 'worker' | 'service' | 'licensed_service';
  status: 'available' | 'adapter_required' | 'licensed_adapter_required';
}

export const requestedAdapterSourceUrls = [
  'https://github.com/buildingSMART',
  'https://github.com/buildingSMART/OpenCDE-API',
  'https://github.com/buildingSMART/IFC',
  'https://github.com/buildingSMART/bSDD',
  'https://github.com/buildingSMART/IDS',
  'https://github.com/buildingSMART/BCF-API',
  'https://github.com/buildingSMART/BCF-XML',
  'https://github.com/buildingSMART/IFC4.x-development',
  'https://github.com/buildingSMART/IFC4.3.x-sample-models',
  'https://github.com/buildingSMART/Sample-Test-Files',
  'https://github.com/buildingSMART/IFC5-development',
  'https://github.com/buildingSMART/validate',
  'https://github.com/buildingSMART/IDS-Audit-tool',
  'https://github.com/buildingSMART/ifc-gherkin-rules',
  'https://github.com/buildingSMART/IFC4.x-IF',
  'https://github.com/buildingSMART/foundation-API',
  'https://github.com/ThatOpen',
  'https://github.com/Autodesk',
  'https://github.com/TrimbleSolutionsCorporation',
  'https://github.com/mcneel',
  'https://github.com/KoStard/ForgeCAD',
  'https://github.com/pascalorg/editor',
  'https://github.com/blender/blender',
  'https://github.com/DynamoDS/DynamoText',
  'https://github.com/DynamoDS',
  'https://github.com/datadrivenconstruction/OpenConstructionERP',
  'https://github.com/frappe/erpnext',
  'https://github.com/specklesystems',
  'https://github.com/specklesystems/speckle_automate_python_example',
  'https://github.com/specklesystems/speckle-automate-qa_qc_workshop',
  'https://github.com/specklesystems/speckle-automate-checker',
  'https://github.com/specklesystems/speckle-server',
  'https://github.com/schauh11/revit-mcp-server',
  'https://github.com/specklesystems/speckle-connectors-dui',
  'https://github.com/specklesystems/speckle-sharp-sdk',
  'https://github.com/specklesystems/IFC-Exporter',
  'https://github.com/specklesystems/speckle-blender',
  'https://github.com/specklesystems/SpeckleConWorkshop-QAQC',
  'https://github.com/specklesystems/speckle-excel',
  'https://github.com/specklesystems/speckle-sketchup',
  'https://github.com/specklesystems/IFC-Exporter-Rhino',
  'https://github.com/specklesystems/IFC-Exporter-Grasshopper',
  'https://github.com/specklesystems/speckle-powerbi',
  'https://github.com/specklesystems/speckle-sharp',
  'https://github.com/ahujasid/blender-mcp',
  'https://github.com/earthtojake/text-to-cad',
  'https://github.com/symbiontarch/ForgeCAD-archive',
  'https://github.com/jtw465/forgecad-studio-suite',
  'https://github.com/leoyang1984/forgecad-design-skill-plugin',
  'https://github.com/BIM-Tools',
  'https://github.com/helenkwok/openbim-mcp',
  'https://github.com/aspen-cloud/triplit',
  'https://github.com/Adam-CAD/CADAM',
  'https://github.com/KittyCAD/text-to-cad-ui',
  'https://github.com/ctriddell/revit-text-to-braille',
  'https://github.com/antvis',
  'https://github.com/dream-num',
  'https://github.com/dream-num/univer/blob/dev/docs/readme/zh-CN.md',
  'https://developer.tekla.com/documentation/get-started-tekla-structures-open-api',
  'https://www.tekla.com/solutions/design-interoperability/open-api',
] as const;

export const adapterSourceRegistry = [
  source(
    'buildingsmart',
    'https://github.com/buildingSMART',
    'buildingSMART',
    'standards',
    'selected',
    'organization',
    null,
    ['.ifc', '.ids', '.bcf', '.bcfzip'],
    ['import', 'export', 'validate', 'sync'],
    'Canonical openBIM standards organization; use as contract source, not as a runtime parser.',
  ),
  source(
    'buildingsmart-opencde-api',
    'https://github.com/buildingSMART/OpenCDE-API',
    'buildingSMART OpenCDE API',
    'standards',
    'reference_only',
    'archived',
    null,
    ['.ifc', '.bcf', '.ids'],
    ['sync'],
    'Archived and no detected license; keep as historical OpenCDE contract reference only.',
  ),
  source(
    'buildingsmart-ifc',
    'https://github.com/buildingSMART/IFC',
    'buildingSMART IFC schema',
    'standards',
    'reference_only',
    'archived',
    'NOASSERTION',
    ['.ifc', '.ifczip'],
    ['import', 'export', 'validate'],
    'Archived schema management repo; use for schema truth, do not vendor code/content without explicit license review.',
  ),
  source(
    'buildingsmart-bsdd',
    'https://github.com/buildingSMART/bSDD',
    'buildingSMART bSDD',
    'standards',
    'selected',
    'active',
    'MIT',
    ['.json', '.csv'],
    ['import', 'export', 'validate', 'sync'],
    'MIT repository for bSDD documentation and examples; use for classification API/schema contracts.',
  ),
  source(
    'buildingsmart-ids',
    'https://github.com/buildingSMART/IDS',
    'buildingSMART IDS',
    'standards',
    'selected',
    'active',
    'NOASSERTION',
    ['.ids', '.xml'],
    ['import', 'export', 'validate'],
    'Active IDS standard; implement validation through schema/audit adapters and avoid copying unlicensed assets.',
  ),
  source(
    'buildingsmart-bcf-api',
    'https://github.com/buildingSMART/BCF-API',
    'buildingSMART BCF API',
    'standards',
    'selected',
    'active',
    'NOASSERTION',
    ['.bcf', '.bcfzip'],
    ['import', 'export', 'sync'],
    'Active BCF API contract for issue collaboration routes.',
  ),
  source(
    'buildingsmart-bcf-xml',
    'https://github.com/buildingSMART/BCF-XML',
    'buildingSMART BCF XML',
    'standards',
    'selected',
    'active',
    'NOASSERTION',
    ['.bcf', '.bcfzip', '.xml'],
    ['import', 'export', 'validate'],
    'Active BCF XML contract for file exchange and validation.',
  ),
  source(
    'buildingsmart-ifc4x-development',
    'https://github.com/buildingSMART/IFC4.x-development',
    'buildingSMART IFC4.x development',
    'standards',
    'reference_only',
    'active',
    'NOASSERTION',
    ['.ifc'],
    ['validate'],
    'IFC4.3 update workstream; use for roadmap/schema tracking, not runtime dependency.',
  ),
  source(
    'buildingsmart-ifc43-sample-models',
    'https://github.com/buildingSMART/IFC4.3.x-sample-models',
    'buildingSMART IFC4.3 sample models',
    'sample_data',
    'sample_data',
    'active',
    null,
    ['.ifc'],
    ['import', 'validate'],
    'Sample models for test fixtures only after fixture license and attribution are recorded.',
  ),
  source(
    'buildingsmart-sample-test-files',
    'https://github.com/buildingSMART/Sample-Test-Files',
    'buildingSMART Sample Test Files',
    'sample_data',
    'sample_data',
    'active',
    'NOASSERTION',
    ['.ifc', '.ids', '.bcf'],
    ['import', 'validate'],
    'Sample files for compatibility tests; store as external fixtures with attribution.',
  ),
  source(
    'buildingsmart-ifc5-development',
    'https://github.com/buildingSMART/IFC5-development',
    'buildingSMART IFC5 development',
    'standards',
    'reference_only',
    'active',
    null,
    ['.ifc'],
    ['validate'],
    'Forward-looking IFC5 workstream; track but do not make production compatibility claims.',
  ),
  source(
    'buildingsmart-validate',
    'https://github.com/buildingSMART/validate',
    'buildingSMART validate',
    'openbim',
    'selected',
    'active',
    'MIT',
    ['.ifc'],
    ['validate'],
    'MIT IFC validation service; priority validation adapter candidate.',
  ),
  source(
    'buildingsmart-ids-audit',
    'https://github.com/buildingSMART/IDS-Audit-tool',
    'buildingSMART IDS Audit tool',
    'openbim',
    'selected',
    'active',
    'MIT',
    ['.ids', '.xml'],
    ['validate'],
    'MIT IDS audit tool; priority IDS validation adapter.',
  ),
  source(
    'buildingsmart-ifc-gherkin-rules',
    'https://github.com/buildingSMART/ifc-gherkin-rules',
    'buildingSMART IFC Gherkin rules',
    'openbim',
    'selected',
    'active',
    'MIT',
    ['.ifc'],
    ['validate'],
    'MIT rule corpus; can drive CI-style IFC validation tests.',
  ),
  source(
    'buildingsmart-ifc4x-if',
    'https://github.com/buildingSMART/IFC4.x-IF',
    'buildingSMART IFC4.x Implementers Forum',
    'standards',
    'reference_only',
    'active',
    null,
    ['.ifc'],
    ['validate'],
    'Implementers forum material; use for interoperability notes only.',
  ),
  source(
    'buildingsmart-foundation-api',
    'https://github.com/buildingSMART/foundation-API',
    'buildingSMART foundation API',
    'standards',
    'reference_only',
    'active',
    null,
    ['.json'],
    ['sync'],
    'Shared API elements; reference when implementing OpenCDE/BCF-style APIs.',
  ),
  source(
    'thatopen',
    'https://github.com/ThatOpen',
    'That Open Company',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.ifc', '.frag'],
    ['viewer', 'online_edit'],
    'Organization-level source; select concrete package repos before vendoring or runtime claims.',
  ),
  source(
    'autodesk',
    'https://github.com/Autodesk',
    'Autodesk',
    'bim_authoring',
    'licensed_gated',
    'organization',
    null,
    ['.rvt', '.rfa', '.dwg'],
    ['import', 'export', 'online_edit', 'automation'],
    'Use through official APS/Revit/AutoCAD credentials and Autodesk terms only.',
  ),
  source(
    'trimble-solutions',
    'https://github.com/TrimbleSolutionsCorporation',
    'Trimble Solutions Corporation',
    'bim_authoring',
    'licensed_gated',
    'organization',
    null,
    ['.ifc', '.tekla'],
    ['import', 'export', 'online_edit', 'automation'],
    'Use through official Trimble/Tekla SDKs, licenses, and partner terms only.',
  ),
  source(
    'mcneel',
    'https://github.com/mcneel',
    'McNeel',
    'bim_authoring',
    'licensed_gated',
    'organization',
    null,
    ['.3dm', '.gh', '.ghx'],
    ['import', 'export', 'online_edit', 'automation'],
    'Rhino/Grasshopper integration must be gated by compatible SDK licenses and user installation.',
  ),
  source(
    'forgecad',
    'https://github.com/KoStard/ForgeCAD',
    'ForgeCAD',
    'cad',
    'reference_only',
    'active',
    'NOASSERTION',
    ['.step', '.stp', '.brep'],
    ['ai_generate', 'export', 'online_edit'],
    'No detected license; can study architecture but must not vendor or depend on it until licensed.',
  ),
  source(
    'pascal-editor',
    'https://github.com/pascalorg/editor',
    'pascalorg editor',
    'cad',
    'selected',
    'active',
    'MIT',
    ['.glb', '.gltf'],
    ['online_edit', 'viewer'],
    'MIT browser architectural editor candidate for UI and scene editing patterns.',
  ),
  source(
    'blender',
    'https://github.com/blender/blender',
    'Blender',
    'cad',
    'selected_external_process',
    'active',
    'GPL-3.0-or-later',
    ['.blend', '.glb', '.gltf', '.obj', '.fbx', '.stl', '.mp4'],
    ['import', 'export', 'online_edit', 'ai_generate', 'automation'],
    'Use as an isolated external process/service; do not link GPL code into the core app.',
  ),
  source(
    'dynamo-text',
    'https://github.com/DynamoDS/DynamoText',
    'DynamoText',
    'bim_authoring',
    'licensed_gated',
    'active',
    'NOASSERTION',
    ['.dyn'],
    ['automation'],
    'Dynamo/Revit ecosystem adapter; gated by Autodesk/Dynamo runtime and license.',
  ),
  source(
    'dynamo',
    'https://github.com/DynamoDS',
    'DynamoDS',
    'bim_authoring',
    'licensed_gated',
    'organization',
    null,
    ['.dyn'],
    ['automation', 'online_edit'],
    'Organization-level Dynamo source; runtime use depends on Autodesk/Dynamo installation terms.',
  ),
  source(
    'openconstructionerp',
    'https://github.com/datadrivenconstruction/OpenConstructionERP',
    'OpenConstructionERP',
    'erp',
    'selected_external_process',
    'active',
    'AGPL-3.0-declared',
    ['.csv', '.xlsx', '.ifc'],
    ['import', 'export', 'sync'],
    'AGPL-declared ERP reference; use through external service boundary unless project accepts copyleft obligations.',
  ),
  source(
    'erpnext',
    'https://github.com/frappe/erpnext',
    'ERPNext',
    'erp',
    'selected_external_process',
    'active',
    'GPL-3.0',
    ['.csv', '.xlsx'],
    ['import', 'export', 'sync'],
    'GPL ERP system; integrate as external service/API, not vendored core dependency.',
  ),
  source(
    'speckle',
    'https://github.com/specklesystems',
    'Speckle',
    'sync',
    'reference_only',
    'organization',
    null,
    ['.ifc', '.rvt', '.3dm', '.skp', '.xlsx'],
    ['sync', 'automation', 'viewer'],
    'Organization-level source; use concrete Apache-2.0 SDK/exporter repos below for implementation.',
  ),
  source(
    'speckle-automate-python-example',
    'https://github.com/specklesystems/speckle_automate_python_example',
    'Speckle Automate Python example',
    'sync',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc'],
    ['automation', 'validate'],
    'Apache-2.0 automation example; suitable worker template source.',
  ),
  source(
    'speckle-qa-qc-workshop',
    'https://github.com/specklesystems/speckle-automate-qa_qc_workshop',
    'Speckle Automate QA/QC workshop',
    'sync',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc', '.xlsx'],
    ['automation', 'validate'],
    'Apache-2.0 QA/QC workflow reference for validation workers.',
  ),
  source(
    'speckle-automate-checker',
    'https://github.com/specklesystems/speckle-automate-checker',
    'Speckle Automate checker',
    'sync',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc'],
    ['automation', 'validate'],
    'Apache-2.0 checker source for model QA worker design.',
  ),
  source(
    'speckle-server',
    'https://github.com/specklesystems/speckle-server',
    'Speckle Server',
    'sync',
    'reference_only',
    'active',
    'NOASSERTION',
    ['.ifc', '.rvt', '.3dm', '.skp'],
    ['sync', 'viewer'],
    'No detected SPDX license via API; treat as reference until license review is explicit.',
  ),
  source(
    'revit-mcp-server',
    'https://github.com/schauh11/revit-mcp-server',
    'Revit MCP server',
    'mcp',
    'licensed_gated',
    'active',
    'MIT',
    ['.rvt', '.rfa'],
    ['automation', 'online_edit', 'ai_generate'],
    'MIT bridge code, but real Revit runtime is proprietary and must be user-licensed.',
  ),
  source(
    'speckle-connectors-dui',
    'https://github.com/specklesystems/speckle-connectors-dui',
    'Speckle connectors DUI',
    'sync',
    'reference_only',
    'active',
    null,
    ['.ifc', '.rvt', '.3dm', '.skp'],
    ['online_edit', 'sync'],
    'No detected license; UI reference only until license is confirmed.',
  ),
  source(
    'speckle-sharp-sdk',
    'https://github.com/specklesystems/speckle-sharp-sdk',
    'Speckle Sharp SDK',
    'sync',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc', '.rvt', '.3dm'],
    ['import', 'export', 'sync', 'automation'],
    'Apache-2.0 SDK candidate for .NET connector sidecars.',
  ),
  source(
    'speckle-ifc-exporter',
    'https://github.com/specklesystems/IFC-Exporter',
    'Speckle IFC Exporter',
    'openbim',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc'],
    ['export'],
    'Apache-2.0 IFC exporter candidate.',
  ),
  source(
    'speckle-blender',
    'https://github.com/specklesystems/speckle-blender',
    'Speckle Blender',
    'sync',
    'selected_external_process',
    'active',
    'Apache-2.0',
    ['.blend', '.glb', '.gltf'],
    ['import', 'export', 'sync', 'automation'],
    'Use with Blender as an external process/service boundary.',
  ),
  source(
    'specklecon-qaqc',
    'https://github.com/specklesystems/SpeckleConWorkshop-QAQC',
    'SpeckleCon Workshop QAQC',
    'sync',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc'],
    ['automation', 'validate'],
    'Apache-2.0 QA/QC example source.',
  ),
  source(
    'speckle-excel',
    'https://github.com/specklesystems/speckle-excel',
    'Speckle Excel',
    'document',
    'reference_only',
    'archived',
    'Apache-2.0',
    ['.xls', '.xlsx'],
    ['import', 'export', 'sync'],
    'Archived Excel connector; use only as historical reference.',
  ),
  source(
    'speckle-sketchup',
    'https://github.com/specklesystems/speckle-sketchup',
    'Speckle SketchUp',
    'bim_authoring',
    'licensed_gated',
    'active',
    'Apache-2.0',
    ['.skp'],
    ['import', 'export', 'sync'],
    'Connector code is Apache-2.0, but SketchUp runtime is a user-licensed desktop product.',
  ),
  source(
    'speckle-ifc-exporter-rhino',
    'https://github.com/specklesystems/IFC-Exporter-Rhino',
    'Speckle IFC Exporter Rhino',
    'bim_authoring',
    'licensed_gated',
    'active',
    'Apache-2.0',
    ['.3dm', '.ifc'],
    ['export'],
    'Apache-2.0 connector, gated by Rhino installation/license.',
  ),
  source(
    'speckle-ifc-exporter-grasshopper',
    'https://github.com/specklesystems/IFC-Exporter-Grasshopper',
    'Speckle IFC Exporter Grasshopper',
    'bim_authoring',
    'licensed_gated',
    'active',
    'Apache-2.0',
    ['.gh', '.ifc'],
    ['export', 'automation'],
    'Apache-2.0 connector, gated by Rhino/Grasshopper runtime.',
  ),
  source(
    'speckle-powerbi',
    'https://github.com/specklesystems/speckle-powerbi',
    'Speckle PowerBI',
    'document',
    'reference_only',
    'active',
    null,
    ['.pbix'],
    ['sync'],
    'No detected license; PowerBI integration remains reference-only.',
  ),
  source(
    'speckle-sharp',
    'https://github.com/specklesystems/speckle-sharp',
    'Speckle Sharp legacy',
    'sync',
    'reference_only',
    'archived',
    'Apache-2.0',
    ['.rvt', '.3dm', '.ifc'],
    ['sync', 'automation'],
    'Archived legacy SDK/connectors; prefer speckle-sharp-sdk for new work.',
  ),
  source(
    'blender-mcp',
    'https://github.com/ahujasid/blender-mcp',
    'Blender MCP',
    'mcp',
    'selected_external_process',
    'active',
    'MIT',
    ['.blend', '.glb', '.gltf', '.obj', '.fbx', '.stl'],
    ['automation', 'ai_generate', 'online_edit'],
    'MIT MCP bridge; execute Blender out of process.',
  ),
  source(
    'text-to-cad',
    'https://github.com/earthtojake/text-to-cad',
    'text-to-cad',
    'ai_generation',
    'selected',
    'active',
    'MIT',
    ['.step', '.stp', '.stl', '.glb'],
    ['ai_generate', 'export'],
    'MIT agent skill source for CAD generation workflows.',
  ),
  source(
    'forgecad-archive',
    'https://github.com/symbiontarch/ForgeCAD-archive',
    'ForgeCAD archive',
    'cad',
    'reference_only',
    'active',
    'NOASSERTION',
    ['.step', '.stp', '.brep'],
    ['ai_generate', 'export'],
    'No detected license; reference-only.',
  ),
  source(
    'forgecad-studio-suite',
    'https://github.com/jtw465/forgecad-studio-suite',
    'ForgeCAD Studio Suite',
    'cad',
    'reference_only',
    'active',
    null,
    ['.step', '.stp', '.brep'],
    ['ai_generate', 'online_edit', 'export'],
    'No detected license; reference-only.',
  ),
  source(
    'forgecad-design-skill-plugin',
    'https://github.com/leoyang1984/forgecad-design-skill-plugin',
    'ForgeCAD design skill plugin',
    'ai_generation',
    'reference_only',
    'active',
    'MIT',
    ['.step', '.stp', '.glb'],
    ['ai_generate'],
    'MIT plugin reference; keep isolated from production until API contract is reviewed.',
  ),
  source(
    'bim-tools',
    'https://github.com/BIM-Tools',
    'BIM-Tools',
    'openbim',
    'reference_only',
    'organization',
    null,
    ['.ifc'],
    ['viewer', 'online_edit'],
    'Organization-level source; choose concrete repos before implementation.',
  ),
  source(
    'openbim-mcp',
    'https://github.com/helenkwok/openbim-mcp',
    'openBIM MCP',
    'mcp',
    'selected',
    'active',
    'MIT',
    ['.ifc', '.ids', '.bcf'],
    ['automation', 'validate', 'ai_generate'],
    'MIT MCP bridge candidate for openBIM operations.',
  ),
  source(
    'triplit',
    'https://github.com/aspen-cloud/triplit',
    'Triplit',
    'sync',
    'selected_external_process',
    'active',
    'AGPL-3.0',
    ['.json'],
    ['sync'],
    'AGPL sync database; use as external service only unless copyleft obligations are accepted.',
  ),
  source(
    'cadam',
    'https://github.com/Adam-CAD/CADAM',
    'CADAM',
    'ai_generation',
    'selected_external_process',
    'active',
    'GPL-3.0',
    ['.step', '.stp', '.stl'],
    ['ai_generate', 'online_edit', 'export'],
    'GPL text-to-CAD application; external process/service only.',
  ),
  source(
    'kittycad-text-to-cad-ui',
    'https://github.com/KittyCAD/text-to-cad-ui',
    'KittyCAD text-to-cad UI',
    'ai_generation',
    'reference_only',
    'archived',
    'MIT',
    ['.step', '.stp', '.stl'],
    ['ai_generate'],
    'Archived UI for Zoo/KittyCAD API; reference only unless current API route is selected.',
  ),
  source(
    'revit-text-to-braille',
    'https://github.com/ctriddell/revit-text-to-braille',
    'Revit text to braille',
    'bim_authoring',
    'licensed_gated',
    'active',
    'MIT',
    ['.rvt', '.rfa', '.dyn'],
    ['automation'],
    'MIT Dynamo workflow but gated by Revit/Dynamo runtime and license.',
  ),
  source(
    'antvis',
    'https://github.com/antvis',
    'AntV',
    'visualization',
    'selected',
    'organization',
    null,
    ['.json', '.mmd', '.drawio', '.svg', '.geojson'],
    ['viewer', 'online_edit', 'export', 'ai_generate'],
    'Organization-level visualization stack; G2/G6/L7 are MIT and active, use concrete packages for graph, flow, map, gantt, and analytic views.',
  ),
  source(
    'dream-num',
    'https://github.com/dream-num',
    'DreamNum',
    'document',
    'reference_only',
    'organization',
    null,
    ['.xlsx', '.csv', '.tsv', '.docx', '.pptx'],
    ['viewer', 'online_edit', 'import', 'export'],
    'Organization source for productivity tooling; select concrete Apache-2.0 Univer packages before runtime dependency claims.',
  ),
  source(
    'dream-num-univer',
    'https://github.com/dream-num/univer/blob/dev/docs/readme/zh-CN.md',
    'Univer',
    'document',
    'selected',
    'active',
    'Apache-2.0',
    ['.xlsx', '.csv', '.tsv', '.docx', '.pptx'],
    ['viewer', 'online_edit', 'import', 'export', 'ai_generate'],
    'Apache-2.0 AI-native productivity suite; use OSS editing core, with import/export/print executed through explicit worker or service adapters.',
  ),
  source(
    'tekla-structures-open-api',
    'https://developer.tekla.com/documentation/get-started-tekla-structures-open-api',
    'Tekla Structures Open API',
    'bim_authoring',
    'licensed_gated',
    'external',
    null,
    ['.ifc', '.tekla'],
    ['import', 'export', 'online_edit', 'automation'],
    'Official docs state a Tekla Structures license is required for Tekla Open API development.',
  ),
  source(
    'tekla-open-api-overview',
    'https://www.tekla.com/solutions/design-interoperability/open-api',
    'Tekla APIs overview',
    'bim_authoring',
    'licensed_gated',
    'external',
    null,
    ['.ifc', '.tekla'],
    ['import', 'export', 'online_edit', 'automation'],
    'Official overview lists Tekla Structures, PowerFab, TSD, Tedds, and Trimble Connect APIs.',
  ),
  source(
    'occt',
    'https://github.com/Open-Cascade-SAS/OCCT',
    'Open Cascade OCCT',
    'cad',
    'selected',
    'active',
    'LGPL-2.1-with-exception',
    ['.step', '.stp', '.iges', '.igs', '.brep'],
    ['import', 'export', 'online_edit', 'ai_generate'],
    'Priority CAD kernel worker dependency for STEP/IGES/BREP import, healing, meshing, and export.',
  ),
  source(
    'cadquery',
    'https://github.com/CadQuery/cadquery',
    'CadQuery',
    'cad',
    'selected',
    'active',
    'Apache-2.0',
    ['.step', '.stp', '.stl'],
    ['ai_generate', 'export'],
    'Priority Python CAD generation worker route.',
  ),
  source(
    'ocp',
    'https://github.com/CadQuery/OCP',
    'CadQuery OCP',
    'cad',
    'selected',
    'active',
    'Apache-2.0',
    ['.step', '.stp', '.iges', '.igs', '.brep'],
    ['import', 'export', 'ai_generate'],
    'OCCT Python binding used by CadQuery-style workers.',
  ),
  source(
    'ifcopenshell',
    'https://github.com/IfcOpenShell/IfcOpenShell',
    'IfcOpenShell',
    'openbim',
    'selected',
    'active',
    'LGPL-3.0',
    ['.ifc', '.ifczip'],
    ['import', 'export', 'validate', 'viewer'],
    'Priority IFC parser, geometry, conversion, and validation worker dependency.',
  ),
  source(
    'stirling-pdf',
    'https://github.com/Stirling-Tools/Stirling-PDF',
    'Stirling PDF',
    'document',
    'selected_external_process',
    'active',
    'MIT',
    ['.pdf', '.pdfa'],
    ['import', 'export', 'online_edit', 'ocr', 'document_conversion'],
    'Priority PDF service adapter for split, merge, OCR, conversion, and derivative jobs.',
  ),
  source(
    'paddleocr',
    'https://github.com/PaddlePaddle/PaddleOCR',
    'PaddleOCR',
    'document',
    'selected',
    'active',
    'Apache-2.0',
    ['.pdf', '.png', '.jpg', '.jpeg', '.webp', '.heic'],
    ['ocr', 'document_conversion'],
    'Priority OCR worker dependency for documents and images.',
  ),
  source(
    'markitdown',
    'https://github.com/microsoft/markitdown',
    'Microsoft MarkItDown',
    'document',
    'selected',
    'active',
    'MIT',
    ['.doc', '.docx', '.ppt', '.pptx', '.xls', '.xlsx', '.pdf'],
    ['import', 'document_conversion'],
    'Priority Office/PDF/media-to-Markdown extraction worker.',
  ),
  source(
    'excelize',
    'https://github.com/qax-os/excelize',
    'Excelize',
    'document',
    'selected',
    'active',
    'BSD-3-Clause',
    ['.xls', '.xlsx', '.xlsm', '.xlsb'],
    ['import', 'export', 'online_edit', 'ai_generate'],
    'Priority spreadsheet read/write/generation sidecar route.',
  ),
] as const satisfies readonly AdapterSource[];

export const formatAdapterRequirements = [
  requirement(
    'pdf',
    ['.pdf', '.pdfa'],
    ['browser PDF viewer', 'Stirling PDF service', 'PaddleOCR worker'],
    ['stirling-pdf', 'paddleocr', 'markitdown'],
    'direct_browser',
    'service',
    'provider',
    'service',
    'available',
  ),
  requirement(
    'image',
    ['.png', '.jpg', '.jpeg', '.svg', '.webp', '.gif', '.heic'],
    ['browser image viewer', 'PaddleOCR worker', 'image generation provider'],
    ['paddleocr'],
    'direct_browser',
    'worker',
    'provider',
    'worker',
    'available',
  ),
  requirement(
    'video',
    ['.mp4', '.webm', '.mov', '.mkv'],
    ['browser video viewer', 'transcode worker', 'video generation provider'],
    ['blender', 'blender-mcp'],
    'direct_browser',
    'worker',
    'provider',
    'worker',
    'available',
  ),
  requirement(
    'voice',
    ['.wav', '.mp3', '.m4a', '.flac', '.ogg', '.aac'],
    ['browser audio viewer', 'ASR/TTS provider', 'audio worker'],
    ['markitdown'],
    'direct_browser',
    'worker',
    'provider',
    'worker',
    'available',
  ),
  requirement(
    'office-document',
    ['.doc', '.docx', '.odt', '.rtf', '.ppt', '.pptx', '.odp'],
    [
      'LibreOffice preview',
      'MarkItDown worker',
      'Univer editing service',
      'template generation worker',
    ],
    ['markitdown', 'dream-num-univer'],
    'worker',
    'worker',
    'provider',
    'worker',
    'adapter_required',
  ),
  requirement(
    'spreadsheet',
    ['.xls', '.xlsx', '.xlsm', '.xlsb', '.ods'],
    [
      'LibreOffice preview',
      'Excelize sidecar',
      'Univer Sheets editing service',
      'schema generation worker',
    ],
    ['excelize', 'markitdown', 'dream-num-univer', 'speckle-excel'],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'openbim',
    ['.ifc', '.ifczip', '.ids', '.bcf', '.bcfzip'],
    [
      'buildingSMART contract',
      'IfcOpenShell worker',
      'buildingSMART validate/IDS audit',
    ],
    [
      'buildingsmart',
      'buildingsmart-ids',
      'buildingsmart-bcf-api',
      'buildingsmart-bcf-xml',
      'ifcopenshell',
      'buildingsmart-validate',
      'buildingsmart-ids-audit',
    ],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'revit-autodesk',
    ['.rvt', '.rfa'],
    ['Autodesk APS/Revit adapter', 'Revit MCP bridge'],
    ['autodesk', 'revit-mcp-server', 'revit-text-to-braille'],
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_adapter_required',
  ),
  requirement(
    'tekla-trimble',
    ['.tekla'],
    ['Tekla Structures Open API adapter', 'Trimble Connect adapter'],
    [
      'trimble-solutions',
      'tekla-structures-open-api',
      'tekla-open-api-overview',
    ],
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_adapter_required',
  ),
  requirement(
    'rhino-grasshopper',
    ['.3dm', '.gh', '.ghx'],
    ['Rhino/Grasshopper licensed sidecar', 'Speckle Rhino exporter'],
    [
      'mcneel',
      'speckle-ifc-exporter-rhino',
      'speckle-ifc-exporter-grasshopper',
    ],
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_adapter_required',
  ),
  requirement(
    'cad-drawing',
    ['.dwg', '.dxf'],
    ['licensed DWG adapter', 'DXF parser worker', 'Autodesk APS boundary'],
    ['autodesk'],
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_adapter_required',
  ),
  requirement(
    'cad-kernel',
    ['.step', '.stp', '.iges', '.igs', '.brep'],
    ['OCCT worker', 'OCP Python binding', 'CadQuery generation worker'],
    ['occt', 'ocp', 'cadquery', 'text-to-cad', 'cadam'],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'mesh-scene',
    ['.glb', '.gltf', '.stl', '.obj', '.fbx', '.skp'],
    ['Three.js viewer', 'Blender service', 'mesh conversion worker'],
    ['blender', 'blender-mcp', 'speckle-blender', 'pascal-editor'],
    'direct_browser',
    'worker',
    'worker',
    'worker',
    'available',
  ),
  requirement(
    'blender-scene',
    ['.blend'],
    ['Blender external process', 'Blender MCP bridge', 'mesh export worker'],
    ['blender', 'blender-mcp', 'speckle-blender'],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'bim-automation',
    ['.dyn'],
    ['Dynamo licensed runtime', 'Dynamo/Revit automation bridge'],
    ['dynamo', 'dynamo-text', 'revit-text-to-braille'],
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_adapter_required',
  ),
  requirement(
    'cnc-machine',
    ['.nc'],
    ['CNC/G-code parser worker', 'production routing adapter'],
    ['occt'],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'point-cloud-reality',
    ['.e57', '.las', '.ply', '.spz'],
    ['point-cloud worker', '3D Tiles worker', 'Gaussian Splatting worker'],
    ['blender', 'blender-mcp'],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'gantt-flow-mindmap',
    ['.mermaid', '.mmd', '.json'],
    ['typed graph/schema worker', 'Mermaid/SVG/PDF exporter', 'AntV G6/X6'],
    ['markitdown', 'antvis'],
    'direct_browser',
    'worker',
    'provider',
    'worker',
    'adapter_required',
  ),
] as const satisfies readonly FormatAdapterRequirement[];

function source(
  id: AdapterSource['id'],
  url: AdapterSource['url'],
  label: AdapterSource['label'],
  category: AdapterSource['category'],
  decision: AdapterSource['decision'],
  state: AdapterSource['state'],
  license: AdapterSource['license'],
  formats: AdapterSource['formats'],
  capabilities: AdapterSource['capabilities'],
  note: AdapterSource['note'],
): AdapterSource {
  return {
    id,
    url,
    label,
    category,
    decision,
    state,
    license,
    formats,
    capabilities,
    note,
  };
}

function requirement(
  family: FormatAdapterRequirement['family'],
  extensions: FormatAdapterRequirement['extensions'],
  adapters: FormatAdapterRequirement['adapters'],
  sourceIds: FormatAdapterRequirement['sourceIds'],
  importRoute: FormatAdapterRequirement['importRoute'],
  onlineEditRoute: FormatAdapterRequirement['onlineEditRoute'],
  aiGenerationRoute: FormatAdapterRequirement['aiGenerationRoute'],
  exportRoute: FormatAdapterRequirement['exportRoute'],
  status: FormatAdapterRequirement['status'],
): FormatAdapterRequirement {
  return {
    family,
    extensions,
    adapters,
    sourceIds,
    importRoute,
    onlineEditRoute,
    aiGenerationRoute,
    exportRoute,
    status,
  };
}

export function adapterSourceByUrl(url: string): AdapterSource | undefined {
  return adapterSourceRegistry.find((source) => source.url === url);
}

export function adapterSourceById(id: string): AdapterSource | undefined {
  return adapterSourceRegistry.find((source) => source.id === id);
}

export function normalizeAdapterExtension(value: string): string {
  const trimmed = value.trim().toLowerCase();
  if (!trimmed) return '';
  if (trimmed.startsWith('.')) return trimmed;
  const dot = trimmed.lastIndexOf('.');
  return dot >= 0 ? trimmed.slice(dot) : `.${trimmed}`;
}

export function adapterRequirementForExtension(
  extension: string,
): FormatAdapterRequirement | undefined {
  const ext = normalizeAdapterExtension(extension);
  return formatAdapterRequirements.find((requirement) =>
    requirement.extensions.includes(ext),
  );
}

export function requiredAdaptersForFileName(
  fileName: string,
  mimeType?: string,
): readonly string[] {
  const requirement = adapterRequirementForExtension(fileName);
  if (requirement) return requirement.adapters;

  const mime = mimeType?.toLowerCase() ?? '';
  if (mime.startsWith('image/')) {
    return ['browser image viewer', 'PaddleOCR worker'];
  }
  if (mime.startsWith('video/')) {
    return ['browser video viewer', 'transcode worker'];
  }
  if (mime.startsWith('audio/')) {
    return ['browser audio viewer', 'ASR/TTS provider'];
  }
  if (mime === 'application/pdf') {
    return ['browser PDF viewer', 'Stirling PDF service'];
  }

  return ['registered parser/viewer worker'];
}

export function adapterSourcesForFileName(fileName: string): AdapterSource[] {
  const requirement = adapterRequirementForExtension(fileName);
  if (!requirement) return [];

  return requirement.sourceIds
    .map(adapterSourceById)
    .filter((source): source is AdapterSource => Boolean(source));
}
