// lib/adapter-source-registry.ts - Upstream adapter and format routing registry
// License: Apache-2.0

export type AdapterSourceDecision =
  | 'selected'
  | 'selected_external_process'
  | 'licensed_gated'
  | 'reference_only'
  | 'sample_data'
  | 'blocked_pending_license';

export type AdapterCapability =
  | 'import'
  | 'export'
  | 'online_edit'
  | 'ai_generate'
  | 'validate'
  | 'sync'
  | 'automation'
  | 'viewer'
  | 'ocr'
  | 'document_conversion';

export type AdapterSourceCategory =
  | 'standards'
  | 'openbim'
  | 'cad'
  | 'bim_authoring'
  | 'document'
  | 'erp'
  | 'sync'
  | 'ai_generation'
  | 'mcp'
  | 'sample_data'
  | 'visualization'
  | 'gis'
  | 'media'
  | 'image'
  | 'office'
  | 'infra';

export type AdapterSourceState =
  | 'active'
  | 'archived'
  | 'organization'
  | 'external';

export interface AdapterSource {
  id: string;
  url: string;
  label: string;
  category: AdapterSourceCategory;
  decision: AdapterSourceDecision;
  state: AdapterSourceState;
  license: string | null;
  formats: readonly string[];
  capabilities: readonly AdapterCapability[];
  note: string;
}

export interface FormatAdapterRequirement {
  family: string;
  extensions: readonly string[];
  adapters: readonly string[];
  sourceIds: readonly string[];
  importRoute: 'direct_browser' | 'worker' | 'service' | 'licensed_service';
  onlineEditRoute: 'native' | 'worker' | 'service' | 'licensed_service';
  aiGenerationRoute: 'worker' | 'provider' | 'licensed_service';
  exportRoute: 'direct' | 'worker' | 'service' | 'licensed_service';
  status: 'available' | 'adapter_required' | 'licensed_adapter_required';
}

export const requestedAdapterSourceUrls = [
  'https://github.com/buildingSMART',
  'https://github.com/buildingSMART/OpenCDE-API',
  'https://github.com/buildingSMART/IFC',
  'https://www.buildingsmart.org/standards/bsi-standards/information-delivery-manual/',
  'https://github.com/buildingSMART/bSDD',
  'https://github.com/buildingSMART/IDS',
  'https://github.com/buildingSMART/BCF-API',
  'https://github.com/buildingSMART/BCF-XML',
  'https://github.com/buildingSMART/IFC4.x-development',
  'https://github.com/buildingSMART/IFC4.3.x-sample-models',
  'https://github.com/buildingSMART/Sample-Test-Files',
  'https://github.com/buildingSMART/IFC5-development',
  'https://github.com/buildingSMART/validate',
  'https://github.com/buildingSMART/IDS-Audit-tool',
  'https://github.com/buildingSMART/ifc-gherkin-rules',
  'https://github.com/buildingSMART/IFC4.x-IF',
  'https://github.com/buildingSMART/foundation-API',
  'https://github.com/ThatOpen',
  'https://github.com/Autodesk',
  'https://github.com/TrimbleSolutionsCorporation',
  'https://github.com/mcneel',
  'https://github.com/KoStard/ForgeCAD',
  'https://github.com/pascalorg/editor',
  'https://github.com/blender/blender',
  'https://github.com/DynamoDS/DynamoText',
  'https://github.com/DynamoDS',
  'https://github.com/datadrivenconstruction/OpenConstructionERP',
  'https://github.com/frappe/erpnext',
  'https://github.com/specklesystems',
  'https://github.com/specklesystems/speckle_automate_python_example',
  'https://github.com/specklesystems/speckle-automate-qa_qc_workshop',
  'https://github.com/specklesystems/speckle-automate-checker',
  'https://github.com/specklesystems/speckle-server',
  'https://github.com/schauh11/revit-mcp-server',
  'https://github.com/specklesystems/speckle-connectors-dui',
  'https://github.com/specklesystems/speckle-sharp-sdk',
  'https://github.com/specklesystems/IFC-Exporter',
  'https://github.com/specklesystems/speckle-blender',
  'https://github.com/specklesystems/SpeckleConWorkshop-QAQC',
  'https://github.com/specklesystems/speckle-excel',
  'https://github.com/specklesystems/speckle-sketchup',
  'https://github.com/specklesystems/IFC-Exporter-Rhino',
  'https://github.com/specklesystems/IFC-Exporter-Grasshopper',
  'https://github.com/specklesystems/speckle-powerbi',
  'https://github.com/specklesystems/speckle-sharp',
  'https://github.com/ahujasid/blender-mcp',
  'https://github.com/earthtojake/text-to-cad',
  'https://github.com/gumyr/build123d',
  'https://github.com/FreeCAD/FreeCAD',
  'https://github.com/LibreCAD/LibreCAD',
  'https://github.com/qcad/qcad',
  'https://github.com/LibreDWG/libredwg',
  'https://github.com/openscad/openscad',
  'https://github.com/microsoft/maker.js',
  'https://github.com/symbiontarch/ForgeCAD-archive',
  'https://github.com/jtw465/forgecad-studio-suite',
  'https://github.com/leoyang1984/forgecad-design-skill-plugin',
  'https://github.com/BIM-Tools',
  'https://github.com/helenkwok/openbim-mcp',
  'https://github.com/aspen-cloud/triplit',
  'https://github.com/Adam-CAD/CADAM',
  'https://github.com/atopile/atopile',
  'https://github.com/LibrePCB/LibrePCB',
  'https://github.com/YosysHQ/oss-cad-suite-build',
  'https://github.com/DeeJoin/IFCDB-Agent',
  'https://github.com/KittyCAD/text-to-cad-ui',
  'https://github.com/caddyserver/caddy',
  'https://github.com/ctriddell/revit-text-to-braille',
  'https://github.com/peazip/PeaZip-Translations',
  'https://github.com/peazip/PeaZip',
  'https://github.com/M2Team/NanaZip',
  'https://github.com/abhigyanpatwari/GitNexus',
  'https://github.com/antvis',
  'https://github.com/antvis/G2',
  'https://github.com/antvis/G6',
  'https://github.com/antvis/chart-visualization-skills',
  'https://github.com/antvis/AVA',
  'https://github.com/antvis/Infographic',
  'https://github.com/dream-num',
  'https://github.com/dream-num/univer/blob/dev/docs/readme/zh-CN.md',
  'https://github.com/CollaboraOnline/online',
  'https://github.com/ONLYOFFICE/DocumentServer',
  'https://github.com/docling-project/docling',
  'https://github.com/Unstructured-IO/unstructured',
  'https://github.com/VikParuchuri/marker',
  'https://github.com/Stirling-Tools/Stirling-PDF',
  'https://github.com/mozilla/pdf.js',
  'https://github.com/ArtifexSoftware/mupdf',
  'https://github.com/opencv/opencv',
  'https://github.com/ImageMagick/ImageMagick',
  'https://github.com/lovell/sharp',
  'https://github.com/FFmpeg/FFmpeg',
  'https://github.com/OSGeo/gdal',
  'https://github.com/PDAL/PDAL',
  'https://github.com/maplibre/maplibre-gl-js',
  'https://github.com/mrdoob',
  'https://github.com/mrdoob/three.js',
  'https://github.com/pmndrs',
  'https://github.com/pmndrs/react-three-fiber',
  'https://github.com/BabylonJS',
  'https://github.com/BabylonJS/Babylon.js',
  'https://github.com/BabylonJS/Editor',
  'https://github.com/BabylonJS/BabylonNative',
  'https://github.com/BabylonJS/BabylonReactNative',
  'https://github.com/BabylonJS/Exporters',
  'https://github.com/BabylonJS/Extensions',
  'https://github.com/NASA-AMMOS',
  'https://github.com/NASA-AMMOS/3DTilesRendererJS',
  'https://github.com/CesiumGS',
  'https://github.com/CesiumGS/cesium',
  'https://github.com/pixijs',
  'https://github.com/pixijs/pixijs',
  'https://github.com/xtermjs',
  'https://github.com/xtermjs/xterm.js',
  'https://github.com/google',
  'https://github.com/google/filament',
  'https://github.com/lettier',
  'https://github.com/lettier/3d-game-shaders-for-beginners',
  'https://github.com/tensorflow',
  'https://github.com/tensorflow/tfjs',
  'https://github.com/plotly',
  'https://github.com/plotly/plotly.js',
  'https://github.com/louistrue',
  'https://github.com/louistrue/ifc-lite',
  'https://github.com/ThatOpen/engine_web-ifc',
  'https://github.com/ThatOpen/engine_ui-components',
  'https://github.com/ThatOpen/web-ifc-three',
  'https://developer.tekla.com/documentation/get-started-tekla-structures-open-api',
  'https://www.tekla.com/solutions/design-interoperability/open-api',
] as const;

export const adapterSourceRegistry = [
  source(
    'buildingsmart',
    'https://github.com/buildingSMART',
    'buildingSMART',
    'standards',
    'selected',
    'organization',
    null,
    ['.ifc', '.ids', '.bcf', '.bcfzip', '.idm'],
    ['import', 'export', 'validate', 'sync'],
    'Canonical openBIM standards organization; use as contract source, not as a runtime parser.',
  ),
  source(
    'buildingsmart-opencde-api',
    'https://github.com/buildingSMART/OpenCDE-API',
    'buildingSMART OpenCDE API',
    'standards',
    'reference_only',
    'archived',
    null,
    ['.ifc', '.bcf', '.ids'],
    ['sync'],
    'Archived and no detected license; keep as historical OpenCDE contract reference only.',
  ),
  source(
    'buildingsmart-ifc',
    'https://github.com/buildingSMART/IFC',
    'buildingSMART IFC schema',
    'standards',
    'reference_only',
    'archived',
    'NOASSERTION',
    ['.ifc', '.ifczip'],
    ['import', 'export', 'validate'],
    'Archived schema management repo; use for schema truth, do not vendor code/content without explicit license review.',
  ),
  source(
    'buildingsmart-idm',
    'https://www.buildingsmart.org/standards/bsi-standards/information-delivery-manual/',
    'buildingSMART IDM',
    'standards',
    'selected',
    'active',
    'ISO 29481',
    ['.idm', '.pdf', '.xml', '.json'],
    ['import', 'export', 'validate'],
    'Information Delivery Manual standard; governs process, exchange requirements, actors, milestones, and information flow before IFC/IDS validation.',
  ),
  source(
    'buildingsmart-bsdd',
    'https://github.com/buildingSMART/bSDD',
    'buildingSMART bSDD',
    'standards',
    'selected',
    'active',
    'MIT',
    ['.json', '.csv'],
    ['import', 'export', 'validate', 'sync'],
    'MIT repository for bSDD documentation and examples; use for classification API/schema contracts.',
  ),
  source(
    'buildingsmart-ids',
    'https://github.com/buildingSMART/IDS',
    'buildingSMART IDS',
    'standards',
    'selected',
    'active',
    'NOASSERTION',
    ['.ids', '.xml'],
    ['import', 'export', 'validate'],
    'Active IDS standard; implement validation through schema/audit adapters and avoid copying unlicensed assets.',
  ),
  source(
    'buildingsmart-bcf-api',
    'https://github.com/buildingSMART/BCF-API',
    'buildingSMART BCF API',
    'standards',
    'selected',
    'active',
    'NOASSERTION',
    ['.bcf', '.bcfzip'],
    ['import', 'export', 'sync'],
    'Active BCF API contract for issue collaboration routes.',
  ),
  source(
    'buildingsmart-bcf-xml',
    'https://github.com/buildingSMART/BCF-XML',
    'buildingSMART BCF XML',
    'standards',
    'selected',
    'active',
    'NOASSERTION',
    ['.bcf', '.bcfzip', '.xml'],
    ['import', 'export', 'validate'],
    'Active BCF XML contract for file exchange and validation.',
  ),
  source(
    'buildingsmart-ifc4x-development',
    'https://github.com/buildingSMART/IFC4.x-development',
    'buildingSMART IFC4.x development',
    'standards',
    'reference_only',
    'active',
    'NOASSERTION',
    ['.ifc'],
    ['validate'],
    'IFC4.3 update workstream; use for roadmap/schema tracking, not runtime dependency.',
  ),
  source(
    'buildingsmart-ifc43-sample-models',
    'https://github.com/buildingSMART/IFC4.3.x-sample-models',
    'buildingSMART IFC4.3 sample models',
    'sample_data',
    'sample_data',
    'active',
    null,
    ['.ifc'],
    ['import', 'validate'],
    'Sample models for test fixtures only after fixture license and attribution are recorded.',
  ),
  source(
    'buildingsmart-sample-test-files',
    'https://github.com/buildingSMART/Sample-Test-Files',
    'buildingSMART Sample Test Files',
    'sample_data',
    'sample_data',
    'active',
    'NOASSERTION',
    ['.ifc', '.ids', '.bcf'],
    ['import', 'validate'],
    'Sample files for compatibility tests; store as external fixtures with attribution.',
  ),
  source(
    'buildingsmart-ifc5-development',
    'https://github.com/buildingSMART/IFC5-development',
    'buildingSMART IFC5 development',
    'standards',
    'reference_only',
    'active',
    null,
    ['.ifc'],
    ['validate'],
    'Forward-looking IFC5 workstream; track but do not make production compatibility claims.',
  ),
  source(
    'buildingsmart-validate',
    'https://github.com/buildingSMART/validate',
    'buildingSMART validate',
    'openbim',
    'selected',
    'active',
    'MIT',
    ['.ifc'],
    ['validate'],
    'MIT IFC validation service; priority validation adapter candidate.',
  ),
  source(
    'buildingsmart-ids-audit',
    'https://github.com/buildingSMART/IDS-Audit-tool',
    'buildingSMART IDS Audit tool',
    'openbim',
    'selected',
    'active',
    'MIT',
    ['.ids', '.xml'],
    ['validate'],
    'MIT IDS audit tool; priority IDS validation adapter.',
  ),
  source(
    'buildingsmart-ifc-gherkin-rules',
    'https://github.com/buildingSMART/ifc-gherkin-rules',
    'buildingSMART IFC Gherkin rules',
    'openbim',
    'selected',
    'active',
    'MIT',
    ['.ifc'],
    ['validate'],
    'MIT rule corpus; can drive CI-style IFC validation tests.',
  ),
  source(
    'buildingsmart-ifc4x-if',
    'https://github.com/buildingSMART/IFC4.x-IF',
    'buildingSMART IFC4.x Implementers Forum',
    'standards',
    'reference_only',
    'active',
    null,
    ['.ifc'],
    ['validate'],
    'Implementers forum material; use for interoperability notes only.',
  ),
  source(
    'buildingsmart-foundation-api',
    'https://github.com/buildingSMART/foundation-API',
    'buildingSMART foundation API',
    'standards',
    'reference_only',
    'active',
    null,
    ['.json'],
    ['sync'],
    'Shared API elements; reference when implementing OpenCDE/BCF-style APIs.',
  ),
  source(
    'thatopen',
    'https://github.com/ThatOpen',
    'That Open Company',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.ifc', '.frag'],
    ['viewer', 'online_edit'],
    'Organization-level source; select concrete package repos before vendoring or runtime claims.',
  ),
  source(
    'autodesk',
    'https://github.com/Autodesk',
    'Autodesk',
    'bim_authoring',
    'licensed_gated',
    'organization',
    null,
    ['.rvt', '.rfa', '.dwg'],
    ['import', 'export', 'online_edit', 'automation'],
    'Use through official APS/Revit/AutoCAD credentials and Autodesk terms only.',
  ),
  source(
    'trimble-solutions',
    'https://github.com/TrimbleSolutionsCorporation',
    'Trimble Solutions Corporation',
    'bim_authoring',
    'licensed_gated',
    'organization',
    null,
    ['.ifc', '.tekla'],
    ['import', 'export', 'online_edit', 'automation'],
    'Use through official Trimble/Tekla SDKs, licenses, and partner terms only.',
  ),
  source(
    'mcneel',
    'https://github.com/mcneel',
    'McNeel',
    'bim_authoring',
    'licensed_gated',
    'organization',
    null,
    ['.3dm', '.gh', '.ghx'],
    ['import', 'export', 'online_edit', 'automation'],
    'Rhino/Grasshopper integration must be gated by compatible SDK licenses and user installation.',
  ),
  source(
    'forgecad',
    'https://github.com/KoStard/ForgeCAD',
    'ForgeCAD',
    'cad',
    'selected_external_process',
    'active',
    'public repo plus hosted/CLI terms',
    ['.forge.js', '.forge.ts', '.step', '.stp', '.stl', '.brep', '.png'],
    ['ai_generate', 'export', 'online_edit', 'viewer'],
    'Capability-priority primary Text-to-CAD route through isolated ForgeCAD service or CLI process; completed jobs must produce real CAD/render artifacts.',
  ),
  source(
    'pascal-editor',
    'https://github.com/pascalorg/editor',
    'pascalorg editor',
    'cad',
    'selected',
    'active',
    'MIT',
    ['.glb', '.gltf'],
    ['online_edit', 'viewer'],
    'MIT browser architectural editor candidate for UI and scene editing patterns.',
  ),
  source(
    'blender',
    'https://github.com/blender/blender',
    'Blender',
    'cad',
    'selected_external_process',
    'active',
    'GPL-3.0-or-later',
    ['.blend', '.glb', '.gltf', '.obj', '.fbx', '.stl', '.mp4'],
    ['import', 'export', 'online_edit', 'ai_generate', 'automation'],
    'Use as an isolated external process/service; do not link GPL code into the core app.',
  ),
  source(
    'dynamo-text',
    'https://github.com/DynamoDS/DynamoText',
    'DynamoText',
    'bim_authoring',
    'licensed_gated',
    'active',
    'NOASSERTION',
    ['.dyn'],
    ['automation'],
    'Dynamo/Revit ecosystem adapter; gated by Autodesk/Dynamo runtime and license.',
  ),
  source(
    'dynamo',
    'https://github.com/DynamoDS',
    'DynamoDS',
    'bim_authoring',
    'licensed_gated',
    'organization',
    null,
    ['.dyn'],
    ['automation', 'online_edit'],
    'Organization-level Dynamo source; runtime use depends on Autodesk/Dynamo installation terms.',
  ),
  source(
    'openconstructionerp',
    'https://github.com/datadrivenconstruction/OpenConstructionERP',
    'OpenConstructionERP',
    'erp',
    'selected_external_process',
    'active',
    'AGPL-3.0-declared',
    ['.csv', '.xlsx', '.ifc'],
    ['import', 'export', 'sync'],
    'AGPL-declared ERP reference; use through external service boundary unless project accepts copyleft obligations.',
  ),
  source(
    'erpnext',
    'https://github.com/frappe/erpnext',
    'ERPNext',
    'erp',
    'selected_external_process',
    'active',
    'GPL-3.0',
    ['.csv', '.xlsx'],
    ['import', 'export', 'sync'],
    'GPL ERP system; integrate as external service/API, not vendored core dependency.',
  ),
  source(
    'speckle',
    'https://github.com/specklesystems',
    'Speckle',
    'sync',
    'reference_only',
    'organization',
    null,
    ['.ifc', '.rvt', '.3dm', '.skp', '.xlsx'],
    ['sync', 'automation', 'viewer'],
    'Organization-level source; use concrete Apache-2.0 SDK/exporter repos below for implementation.',
  ),
  source(
    'speckle-automate-python-example',
    'https://github.com/specklesystems/speckle_automate_python_example',
    'Speckle Automate Python example',
    'sync',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc'],
    ['automation', 'validate'],
    'Apache-2.0 automation example; suitable worker template source.',
  ),
  source(
    'speckle-qa-qc-workshop',
    'https://github.com/specklesystems/speckle-automate-qa_qc_workshop',
    'Speckle Automate QA/QC workshop',
    'sync',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc', '.xlsx'],
    ['automation', 'validate'],
    'Apache-2.0 QA/QC workflow reference for validation workers.',
  ),
  source(
    'speckle-automate-checker',
    'https://github.com/specklesystems/speckle-automate-checker',
    'Speckle Automate checker',
    'sync',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc'],
    ['automation', 'validate'],
    'Apache-2.0 checker source for model QA worker design.',
  ),
  source(
    'speckle-server',
    'https://github.com/specklesystems/speckle-server',
    'Speckle Server',
    'sync',
    'selected_external_process',
    'active',
    'service-reviewed',
    ['.ifc', '.rvt', '.3dm', '.skp'],
    ['sync', 'viewer', 'automation'],
    'Capability-priority model collaboration route through an isolated Speckle Server/API service; do not vendor server code into core.',
  ),
  source(
    'revit-mcp-server',
    'https://github.com/schauh11/revit-mcp-server',
    'Revit MCP server',
    'mcp',
    'licensed_gated',
    'active',
    'MIT',
    ['.rvt', '.rfa'],
    ['automation', 'online_edit', 'ai_generate'],
    'MIT bridge code, but real Revit runtime is proprietary and must be user-licensed.',
  ),
  source(
    'speckle-connectors-dui',
    'https://github.com/specklesystems/speckle-connectors-dui',
    'Speckle connectors DUI',
    'sync',
    'reference_only',
    'active',
    null,
    ['.ifc', '.rvt', '.3dm', '.skp'],
    ['online_edit', 'sync'],
    'Connector UI design reference only; production sync uses Speckle Server/API and concrete SDK/exporter routes.',
  ),
  source(
    'speckle-sharp-sdk',
    'https://github.com/specklesystems/speckle-sharp-sdk',
    'Speckle Sharp SDK',
    'sync',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc', '.rvt', '.3dm'],
    ['import', 'export', 'sync', 'automation'],
    'Apache-2.0 SDK candidate for .NET connector sidecars.',
  ),
  source(
    'speckle-ifc-exporter',
    'https://github.com/specklesystems/IFC-Exporter',
    'Speckle IFC Exporter',
    'openbim',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc'],
    ['export'],
    'Apache-2.0 IFC exporter candidate.',
  ),
  source(
    'speckle-blender',
    'https://github.com/specklesystems/speckle-blender',
    'Speckle Blender',
    'sync',
    'selected_external_process',
    'active',
    'Apache-2.0',
    ['.blend', '.glb', '.gltf'],
    ['import', 'export', 'sync', 'automation'],
    'Use with Blender as an external process/service boundary.',
  ),
  source(
    'specklecon-qaqc',
    'https://github.com/specklesystems/SpeckleConWorkshop-QAQC',
    'SpeckleCon Workshop QAQC',
    'sync',
    'selected',
    'active',
    'Apache-2.0',
    ['.ifc'],
    ['automation', 'validate'],
    'Apache-2.0 QA/QC example source.',
  ),
  source(
    'speckle-excel',
    'https://github.com/specklesystems/speckle-excel',
    'Speckle Excel',
    'document',
    'reference_only',
    'archived',
    'Apache-2.0',
    ['.xls', '.xlsx'],
    ['import', 'export', 'sync'],
    'Archived Excel connector; use only as historical reference.',
  ),
  source(
    'speckle-sketchup',
    'https://github.com/specklesystems/speckle-sketchup',
    'Speckle SketchUp',
    'bim_authoring',
    'licensed_gated',
    'active',
    'Apache-2.0',
    ['.skp'],
    ['import', 'export', 'sync'],
    'Connector code is Apache-2.0, but SketchUp runtime is a user-licensed desktop product.',
  ),
  source(
    'speckle-ifc-exporter-rhino',
    'https://github.com/specklesystems/IFC-Exporter-Rhino',
    'Speckle IFC Exporter Rhino',
    'bim_authoring',
    'licensed_gated',
    'active',
    'Apache-2.0',
    ['.3dm', '.ifc'],
    ['export'],
    'Apache-2.0 connector, gated by Rhino installation/license.',
  ),
  source(
    'speckle-ifc-exporter-grasshopper',
    'https://github.com/specklesystems/IFC-Exporter-Grasshopper',
    'Speckle IFC Exporter Grasshopper',
    'bim_authoring',
    'licensed_gated',
    'active',
    'Apache-2.0',
    ['.gh', '.ifc'],
    ['export', 'automation'],
    'Apache-2.0 connector, gated by Rhino/Grasshopper runtime.',
  ),
  source(
    'speckle-powerbi',
    'https://github.com/specklesystems/speckle-powerbi',
    'Speckle PowerBI',
    'document',
    'reference_only',
    'active',
    null,
    ['.pbix'],
    ['sync'],
    'PowerBI-specific route remains reference-only until a licensed enterprise BI adapter is selected.',
  ),
  source(
    'speckle-sharp',
    'https://github.com/specklesystems/speckle-sharp',
    'Speckle Sharp legacy',
    'sync',
    'reference_only',
    'archived',
    'Apache-2.0',
    ['.rvt', '.3dm', '.ifc'],
    ['sync', 'automation'],
    'Archived legacy SDK/connectors; prefer speckle-sharp-sdk for new work.',
  ),
  source(
    'blender-mcp',
    'https://github.com/ahujasid/blender-mcp',
    'Blender MCP',
    'mcp',
    'selected_external_process',
    'active',
    'MIT',
    ['.blend', '.glb', '.gltf', '.obj', '.fbx', '.stl'],
    ['automation', 'ai_generate', 'online_edit'],
    'MIT MCP bridge; execute Blender out of process.',
  ),
  source(
    'text-to-cad',
    'https://github.com/earthtojake/text-to-cad',
    'text-to-cad',
    'ai_generation',
    'selected',
    'active',
    'MIT',
    ['.step', '.stp', '.stl', '.glb'],
    ['ai_generate', 'export'],
    'MIT agent skill source for CAD generation workflows.',
  ),
  source(
    'forgecad-archive',
    'https://github.com/symbiontarch/ForgeCAD-archive',
    'ForgeCAD archive',
    'cad',
    'reference_only',
    'active',
    'NOASSERTION',
    ['.step', '.stp', '.brep'],
    ['ai_generate', 'export'],
    'Alternate ForgeCAD archive source; reference-only because KoStard/ForgeCAD is the selected primary route.',
  ),
  source(
    'forgecad-studio-suite',
    'https://github.com/jtw465/forgecad-studio-suite',
    'ForgeCAD Studio Suite',
    'cad',
    'reference_only',
    'active',
    null,
    ['.step', '.stp', '.brep'],
    ['ai_generate', 'online_edit', 'export'],
    'Alternate ForgeCAD studio source; reference-only because KoStard/ForgeCAD is the selected primary route.',
  ),
  source(
    'forgecad-design-skill-plugin',
    'https://github.com/leoyang1984/forgecad-design-skill-plugin',
    'ForgeCAD design skill plugin',
    'ai_generation',
    'reference_only',
    'active',
    'MIT',
    ['.step', '.stp', '.glb'],
    ['ai_generate'],
    'MIT plugin reference; keep isolated from production until API contract is reviewed.',
  ),
  source(
    'bim-tools',
    'https://github.com/BIM-Tools',
    'BIM-Tools',
    'openbim',
    'reference_only',
    'organization',
    null,
    ['.ifc'],
    ['viewer', 'online_edit'],
    'Organization-level source; choose concrete repos before implementation.',
  ),
  source(
    'openbim-mcp',
    'https://github.com/helenkwok/openbim-mcp',
    'openBIM MCP',
    'mcp',
    'selected',
    'active',
    'MIT',
    ['.ifc', '.ids', '.bcf'],
    ['automation', 'validate', 'ai_generate'],
    'MIT MCP bridge candidate for openBIM operations.',
  ),
  source(
    'triplit',
    'https://github.com/aspen-cloud/triplit',
    'Triplit',
    'sync',
    'selected_external_process',
    'active',
    'AGPL-3.0',
    ['.json'],
    ['sync'],
    'AGPL sync database; use as external service only unless copyleft obligations are accepted.',
  ),
  source(
    'caddy',
    'https://github.com/caddyserver/caddy',
    'Caddy',
    'infra',
    'selected_external_process',
    'active',
    'Apache-2.0',
    ['.caddyfile'],
    ['automation'],
    'Gateway and reverse-proxy deployment component candidate for production routing, TLS, and service boundary references.',
  ),
  source(
    'cadam',
    'https://github.com/Adam-CAD/CADAM',
    'CADAM',
    'ai_generation',
    'selected_external_process',
    'active',
    'GPL-3.0',
    ['.step', '.stp', '.stl'],
    ['ai_generate', 'online_edit', 'export'],
    'GPL text-to-CAD application; external process/service only.',
  ),
  source(
    'atopile',
    'https://github.com/atopile/atopile',
    'atopile',
    'cad',
    'selected_external_process',
    'active',
    null,
    ['.ato', '.kicad_pcb'],
    ['ai_generate', 'export', 'validate'],
    'Electronics and hardware design generation route candidate behind an isolated toolchain boundary.',
  ),
  source(
    'librepcb',
    'https://github.com/LibrePCB/LibrePCB',
    'LibrePCB',
    'cad',
    'selected_external_process',
    'active',
    'GPL-3.0',
    ['.lppz', '.kicad_pcb'],
    ['import', 'export', 'online_edit'],
    'PCB design ecosystem route candidate; keep copyleft desktop runtime outside core.',
  ),
  source(
    'oss-cad-suite-build',
    'https://github.com/YosysHQ/oss-cad-suite-build',
    'oss-cad-suite-build',
    'cad',
    'selected_external_process',
    'active',
    null,
    ['.v', '.sv', '.json'],
    ['validate', 'export'],
    'Hardware CAD/EDA toolchain packaging reference for isolated worker images.',
  ),
  source(
    'kittycad-text-to-cad-ui',
    'https://github.com/KittyCAD/text-to-cad-ui',
    'KittyCAD text-to-cad UI',
    'ai_generation',
    'reference_only',
    'archived',
    'MIT',
    ['.step', '.stp', '.stl'],
    ['ai_generate'],
    'Archived UI for Zoo/KittyCAD API; reference only unless current API route is selected.',
  ),
  source(
    'revit-text-to-braille',
    'https://github.com/ctriddell/revit-text-to-braille',
    'Revit text to braille',
    'bim_authoring',
    'licensed_gated',
    'active',
    'MIT',
    ['.rvt', '.rfa', '.dyn'],
    ['automation'],
    'MIT Dynamo workflow but gated by Revit/Dynamo runtime and license.',
  ),
  source(
    'antvis',
    'https://github.com/antvis',
    'AntV',
    'visualization',
    'selected',
    'organization',
    null,
    ['.json', '.mmd', '.drawio', '.svg', '.geojson'],
    ['viewer', 'online_edit', 'export', 'ai_generate'],
    'Organization-level visualization stack; G2/G6/L7 are MIT and active, use concrete packages for graph, flow, map, gantt, and analytic views.',
  ),
  source(
    'gitnexus',
    'https://github.com/abhigyanpatwari/GitNexus',
    'GitNexus',
    'visualization',
    'reference_only',
    'active',
    null,
    ['.json', '.md'],
    ['viewer', 'automation'],
    'Workbench layout and AI/knowledge-graph reference: left directory, top toolbar, center content, right chat, and Graph RAG-style context.',
  ),
  source(
    'antvis-g2',
    'https://github.com/antvis/G2',
    'AntV G2',
    'visualization',
    'selected',
    'active',
    'MIT',
    ['.json', '.csv', '.tsv'],
    ['viewer', 'export', 'ai_generate'],
    'Priority analytic chart renderer for project, cost, finance, and production dashboards.',
  ),
  source(
    'antvis-g6',
    'https://github.com/antvis/G6',
    'AntV G6',
    'visualization',
    'selected',
    'active',
    'MIT',
    ['.json', '.mmd', '.drawio'],
    ['viewer', 'online_edit', 'export', 'ai_generate'],
    'Priority graph, flow, topology, mindmap, and dependency visualization route.',
  ),
  source(
    'antvis-chart-visualization-skills',
    'https://github.com/antvis/chart-visualization-skills',
    'AntV chart visualization skills',
    'ai_generation',
    'selected',
    'active',
    'MIT',
    ['.json', '.csv'],
    ['ai_generate', 'viewer'],
    'Chart generation skill source for AI-produced analytics and report visuals.',
  ),
  source(
    'antvis-ava',
    'https://github.com/antvis/AVA',
    'AntV AVA',
    'ai_generation',
    'selected',
    'active',
    'MIT',
    ['.json', '.csv'],
    ['ai_generate', 'viewer'],
    'AI-assisted visualization advisor route for chart recommendation and data insight generation.',
  ),
  source(
    'antvis-infographic',
    'https://github.com/antvis/Infographic',
    'AntV Infographic',
    'visualization',
    'selected',
    'active',
    'MIT',
    ['.svg', '.png', '.json'],
    ['viewer', 'export', 'ai_generate'],
    'Infographic rendering source for management reports and presentation exports.',
  ),
  source(
    'dream-num',
    'https://github.com/dream-num',
    'DreamNum',
    'document',
    'reference_only',
    'organization',
    null,
    ['.xlsx', '.csv', '.tsv', '.docx', '.pptx'],
    ['viewer', 'online_edit', 'import', 'export'],
    'Organization source for productivity tooling; select concrete Apache-2.0 Univer packages before runtime dependency claims.',
  ),
  source(
    'dream-num-univer',
    'https://github.com/dream-num/univer/blob/dev/docs/readme/zh-CN.md',
    'Univer',
    'document',
    'selected',
    'active',
    'Apache-2.0',
    ['.xlsx', '.csv', '.tsv', '.docx', '.pptx'],
    ['viewer', 'online_edit', 'import', 'export', 'ai_generate'],
    'Apache-2.0 AI-native productivity suite; use OSS editing core, with import/export/print executed through explicit worker or service adapters.',
  ),
  source(
    'mrdoob',
    'https://github.com/mrdoob',
    'mrdoob',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.glb', '.gltf', '.stl', '.obj'],
    ['viewer', 'online_edit'],
    'Organization-level source for Three.js; use the concrete three.js repo as the runtime dependency.',
  ),
  source(
    'threejs',
    'https://github.com/mrdoob/three.js',
    'Three.js',
    'visualization',
    'selected',
    'active',
    'MIT',
    ['.glb', '.gltf', '.stl', '.obj', '.fbx', '.ply'],
    ['viewer', 'online_edit', 'export'],
    'Primary browser 3D viewer already wired for GLB, glTF, STL, and converted engineering derivatives.',
  ),
  source(
    'pmndrs',
    'https://github.com/pmndrs',
    'pmndrs',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.glb', '.gltf', '.stl'],
    ['viewer', 'online_edit'],
    'Organization-level React/WebGL ecosystem source; concrete runtime is react-three-fiber.',
  ),
  source(
    'react-three-fiber',
    'https://github.com/pmndrs/react-three-fiber',
    'React Three Fiber',
    'visualization',
    'selected',
    'active',
    'MIT',
    ['.glb', '.gltf', '.stl', '.ifc', '.step', '.stp'],
    ['viewer', 'online_edit'],
    'React renderer already used by the universal engineering viewer and BIM viewport.',
  ),
  source(
    'babylonjs',
    'https://github.com/BabylonJS',
    'BabylonJS',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.glb', '.gltf', '.stl', '.obj', '.fbx'],
    ['viewer', 'online_edit', 'export'],
    'Organization-level 3D engine source; use concrete packages only when Three.js route is insufficient.',
  ),
  source(
    'babylonjs-engine',
    'https://github.com/BabylonJS/Babylon.js',
    'Babylon.js',
    'visualization',
    'selected',
    'active',
    'Apache-2.0',
    ['.glb', '.gltf', '.stl', '.obj', '.fbx'],
    ['viewer', 'online_edit', 'export'],
    'Secondary browser 3D engine candidate for advanced scene editor/runtime work.',
  ),
  source(
    'babylonjs-editor',
    'https://github.com/BabylonJS/Editor',
    'Babylon.js Editor',
    'visualization',
    'reference_only',
    'active',
    null,
    ['.glb', '.gltf'],
    ['online_edit', 'export'],
    'Scene editor reference; do not embed until package/license boundaries are reviewed.',
  ),
  source(
    'babylonjs-native',
    'https://github.com/BabylonJS/BabylonNative',
    'Babylon Native',
    'visualization',
    'reference_only',
    'active',
    null,
    ['.glb', '.gltf'],
    ['viewer'],
    'Native runtime reference for future desktop/mobile shells, not current web runtime.',
  ),
  source(
    'babylonjs-react-native',
    'https://github.com/BabylonJS/BabylonReactNative',
    'Babylon React Native',
    'visualization',
    'reference_only',
    'active',
    null,
    ['.glb', '.gltf'],
    ['viewer'],
    'Mobile/native reference only; web viewer keeps Three.js as primary runtime.',
  ),
  source(
    'babylonjs-exporters',
    'https://github.com/BabylonJS/Exporters',
    'Babylon Exporters',
    'visualization',
    'selected_external_process',
    'active',
    null,
    ['.glb', '.gltf'],
    ['export'],
    'Exporter tooling candidate behind worker/process boundary.',
  ),
  source(
    'babylonjs-extensions',
    'https://github.com/BabylonJS/Extensions',
    'Babylon Extensions',
    'visualization',
    'reference_only',
    'active',
    null,
    ['.glb', '.gltf'],
    ['viewer', 'online_edit'],
    'Extension reference; select concrete extension packages before use.',
  ),
  source(
    'nasa-ammos',
    'https://github.com/NASA-AMMOS',
    'NASA AMMOS',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.b3dm', '.i3dm', '.pnts', '.cmpt'],
    ['viewer'],
    'Organization-level source for 3D Tiles renderer; concrete runtime is 3DTilesRendererJS.',
  ),
  source(
    '3d-tiles-renderer-js',
    'https://github.com/NASA-AMMOS/3DTilesRendererJS',
    '3DTilesRendererJS',
    'visualization',
    'selected',
    'active',
    'Apache-2.0',
    ['.b3dm', '.i3dm', '.pnts', '.cmpt', '.json'],
    ['viewer'],
    'Priority Three.js-based 3D Tiles viewer route for city models, point clouds, and digital twin derivatives.',
  ),
  source(
    'cesiumgs',
    'https://github.com/CesiumGS',
    'CesiumGS',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.b3dm', '.i3dm', '.pnts', '.cmpt', '.kml', '.czml'],
    ['viewer', 'online_edit'],
    'Organization-level Cesium source; use concrete CesiumJS packages for geospatial viewers.',
  ),
  source(
    'cesium',
    'https://github.com/CesiumGS/cesium',
    'CesiumJS',
    'visualization',
    'selected',
    'active',
    'Apache-2.0',
    ['.b3dm', '.i3dm', '.pnts', '.cmpt', '.kml', '.czml', '.geojson'],
    ['viewer', 'online_edit', 'export'],
    'Priority GIS, terrain, 3D Tiles, and reality capture viewer route.',
  ),
  source(
    'pixijs',
    'https://github.com/pixijs',
    'PixiJS',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.png', '.jpg', '.webp', '.svg'],
    ['viewer', 'online_edit'],
    'Organization-level 2D canvas/WebGPU source; concrete runtime is pixijs.',
  ),
  source(
    'pixijs-engine',
    'https://github.com/pixijs/pixijs',
    'PixiJS engine',
    'visualization',
    'selected',
    'active',
    'MIT',
    ['.png', '.jpg', '.webp', '.svg'],
    ['viewer', 'online_edit', 'export'],
    '2D high-performance canvas route for drawings, image annotation, and viewer overlays.',
  ),
  source(
    'xtermjs',
    'https://github.com/xtermjs',
    'xterm.js organization',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.log', '.txt'],
    ['viewer', 'online_edit'],
    'Organization-level terminal UI source; concrete route is xterm.js.',
  ),
  source(
    'xtermjs-terminal',
    'https://github.com/xtermjs/xterm.js',
    'xterm.js',
    'visualization',
    'selected',
    'active',
    'MIT',
    ['.log', '.txt', '.sh'],
    ['viewer', 'online_edit'],
    'Terminal and job-log viewer route for worker, CNC, robot, and deployment logs.',
  ),
  source(
    'google',
    'https://github.com/google',
    'Google open source',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.glb', '.gltf'],
    ['viewer'],
    'Organization-level source; select concrete repos only.',
  ),
  source(
    'google-filament',
    'https://github.com/google/filament',
    'Filament',
    'visualization',
    'selected_external_process',
    'active',
    'Apache-2.0',
    ['.glb', '.gltf'],
    ['viewer', 'export'],
    'Physically based rendering reference and possible external renderer for high-quality model images.',
  ),
  source(
    'lettier',
    'https://github.com/lettier',
    'Lettier',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.glsl'],
    ['viewer'],
    'Shader learning/reference source only.',
  ),
  source(
    'lettier-shaders',
    'https://github.com/lettier/3d-game-shaders-for-beginners',
    '3D Game Shaders For Beginners',
    'visualization',
    'reference_only',
    'active',
    null,
    ['.glsl'],
    ['viewer'],
    'Shader technique reference; no production runtime dependency.',
  ),
  source(
    'tensorflow',
    'https://github.com/tensorflow',
    'TensorFlow',
    'ai_generation',
    'reference_only',
    'organization',
    null,
    ['.json'],
    ['ai_generate', 'viewer'],
    'Organization-level ML source; concrete browser runtime is TensorFlow.js.',
  ),
  source(
    'tensorflow-tfjs',
    'https://github.com/tensorflow/tfjs',
    'TensorFlow.js',
    'ai_generation',
    'selected',
    'active',
    'Apache-2.0',
    ['.json', '.png', '.jpg'],
    ['ai_generate', 'viewer'],
    'Browser ML runtime candidate for lightweight extraction, classification, and annotation assistants.',
  ),
  source(
    'plotly',
    'https://github.com/plotly',
    'Plotly',
    'visualization',
    'reference_only',
    'organization',
    null,
    ['.json', '.csv'],
    ['viewer', 'export'],
    'Organization-level charting source; concrete runtime is plotly.js.',
  ),
  source(
    'plotly-js',
    'https://github.com/plotly/plotly.js',
    'Plotly.js',
    'visualization',
    'selected',
    'active',
    'MIT',
    ['.json', '.csv', '.tsv'],
    ['viewer', 'export'],
    'Engineering and operations charting route where Plotly interactions are a better fit than AntV.',
  ),
  source(
    'louistrue',
    'https://github.com/louistrue',
    'louistrue',
    'openbim',
    'reference_only',
    'organization',
    null,
    ['.ifc'],
    ['viewer', 'validate'],
    'Organization-level IFC tools source; select concrete repos before use.',
  ),
  source(
    'ifc-lite',
    'https://github.com/louistrue/ifc-lite',
    'ifc-lite',
    'openbim',
    'selected',
    'active',
    null,
    ['.ifc'],
    ['viewer', 'validate'],
    'Lightweight IFC parsing/reference route for browser-side checks and fallback diagnostics.',
  ),
  source(
    'thatopen-engine-web-ifc',
    'https://github.com/ThatOpen/engine_web-ifc',
    'ThatOpen engine_web-ifc',
    'openbim',
    'selected',
    'active',
    'MPL-2.0',
    ['.ifc', '.ifczip'],
    ['viewer', 'import', 'export', 'validate'],
    'Browser IFC WASM runtime already wired through web-ifc for source geometry preview.',
  ),
  source(
    'thatopen-engine-ui-components',
    'https://github.com/ThatOpen/engine_ui-components',
    'ThatOpen UI components',
    'visualization',
    'reference_only',
    'active',
    'MIT',
    ['.ifc'],
    ['viewer', 'online_edit'],
    'BIM UI composition reference; use patterns without adopting wholesale until design review.',
  ),
  source(
    'thatopen-web-ifc-three',
    'https://github.com/ThatOpen/web-ifc-three',
    'web-ifc-three',
    'openbim',
    'selected',
    'active',
    null,
    ['.ifc'],
    ['viewer'],
    'IFC to Three.js integration reference for browser BIM viewers.',
  ),
  source(
    'tekla-structures-open-api',
    'https://developer.tekla.com/documentation/get-started-tekla-structures-open-api',
    'Tekla Structures Open API',
    'bim_authoring',
    'licensed_gated',
    'external',
    null,
    ['.ifc', '.tekla'],
    ['import', 'export', 'online_edit', 'automation'],
    'Official docs state a Tekla Structures license is required for Tekla Open API development.',
  ),
  source(
    'tekla-open-api-overview',
    'https://www.tekla.com/solutions/design-interoperability/open-api',
    'Tekla APIs overview',
    'bim_authoring',
    'licensed_gated',
    'external',
    null,
    ['.ifc', '.tekla'],
    ['import', 'export', 'online_edit', 'automation'],
    'Official overview lists Tekla Structures, PowerFab, TSD, Tedds, and Trimble Connect APIs.',
  ),
  source(
    'occt',
    'https://github.com/Open-Cascade-SAS/OCCT',
    'Open Cascade OCCT',
    'cad',
    'selected',
    'active',
    'LGPL-2.1-with-exception',
    ['.step', '.stp', '.iges', '.igs', '.brep'],
    ['import', 'export', 'online_edit', 'ai_generate'],
    'Priority CAD kernel worker dependency for STEP/IGES/BREP import, healing, meshing, and export.',
  ),
  source(
    'cadquery',
    'https://github.com/CadQuery/cadquery',
    'CadQuery',
    'cad',
    'selected',
    'active',
    'Apache-2.0',
    ['.step', '.stp', '.stl'],
    ['ai_generate', 'export'],
    'Priority Python CAD generation worker route.',
  ),
  source(
    'build123d',
    'https://github.com/gumyr/build123d',
    'build123d',
    'cad',
    'selected',
    'active',
    'Apache-2.0',
    ['.step', '.stp', '.stl'],
    ['ai_generate', 'export'],
    'Selected as the safer structured Text-to-CAD worker route alongside CadQuery; arbitrary user Python is not executed.',
  ),
  source(
    'ocp',
    'https://github.com/CadQuery/OCP',
    'CadQuery OCP',
    'cad',
    'selected',
    'active',
    'Apache-2.0',
    ['.step', '.stp', '.iges', '.igs', '.brep'],
    ['import', 'export', 'ai_generate'],
    'OCCT Python binding used by CadQuery-style workers.',
  ),
  source(
    'freecad',
    'https://github.com/FreeCAD/FreeCAD',
    'FreeCAD',
    'cad',
    'selected_external_process',
    'active',
    'LGPL-2.1',
    ['.step', '.stp', '.iges', '.igs', '.brep', '.stl', '.fcstd'],
    ['import', 'export', 'online_edit'],
    'Headless FreeCAD conversion is selected only as an external process/container boundary.',
  ),
  source(
    'libredwg',
    'https://github.com/LibreDWG/libredwg',
    'LibreDWG',
    'cad',
    'selected_external_process',
    'active',
    'GPL-3.0',
    ['.dwg', '.dxf'],
    ['import', 'export'],
    'DWG fallback candidate only behind a GPL-isolated sidecar; core DWG remains licensed-service gated.',
  ),
  source(
    'librecad',
    'https://github.com/LibreCAD/LibreCAD',
    'LibreCAD',
    'cad',
    'selected_external_process',
    'active',
    'GPL-2.0',
    ['.dxf', '.dwg'],
    ['viewer', 'import', 'export'],
    'DXF layer, block, dimension, and text behavior reference; runtime use stays isolated or clean-room.',
  ),
  source(
    'qcad',
    'https://github.com/qcad/qcad',
    'QCAD',
    'cad',
    'selected_external_process',
    'active',
    'GPL-3.0',
    ['.dxf', '.dwg'],
    ['viewer', 'import', 'export'],
    'DXF/DWG conversion and viewer behavior candidate behind an external process boundary.',
  ),
  source(
    'openscad',
    'https://github.com/openscad/openscad',
    'OpenSCAD',
    'cad',
    'selected_external_process',
    'active',
    'GPL-2.0',
    ['.scad', '.stl', '.csg'],
    ['ai_generate', 'export'],
    'Scripted parametric CAD generation route; execute only in an isolated worker.',
  ),
  source(
    'makerjs',
    'https://github.com/microsoft/maker.js',
    'Maker.js',
    'cad',
    'selected',
    'active',
    'MIT',
    ['.dxf', '.svg'],
    ['ai_generate', 'export', 'viewer'],
    'Browser/worker 2D CAD generation route candidate for DXF/SVG artifacts.',
  ),
  source(
    'ifcopenshell',
    'https://github.com/IfcOpenShell/IfcOpenShell',
    'IfcOpenShell',
    'openbim',
    'selected',
    'active',
    'LGPL-3.0',
    ['.ifc', '.ifczip'],
    ['import', 'export', 'validate', 'viewer'],
    'Priority IFC parser, geometry, conversion, and validation worker dependency.',
  ),
  source(
    'ifcdb-agent',
    'https://github.com/DeeJoin/IFCDB-Agent',
    'IFCDB-Agent',
    'openbim',
    'selected_external_process',
    'active',
    null,
    ['.ifc', '.ifczip'],
    ['import', 'export', 'validate', 'automation'],
    'Required IFC database, object graph, query, export, clash, quantity, and agent target for the openBIM CDE layer; run behind the isolated ifcdb_agent service/worker boundary pinned to https://github.com/DeeJoin/IFCDB-Agent/releases/tag/v1.0.9.',
  ),
  source(
    'docling',
    'https://github.com/docling-project/docling',
    'Docling',
    'document',
    'selected',
    'active',
    'MIT',
    ['.pdf', '.docx', '.pptx', '.xlsx', '.html', '.png', '.jpg'],
    ['import', 'ocr', 'document_conversion'],
    'Selected as the default permissive document/PDF structure worker before heavier AGPL/OCR routes.',
  ),
  source(
    'peazip',
    'https://github.com/peazip/PeaZip',
    'PeaZip',
    'document',
    'selected_external_process',
    'active',
    'LGPL-3.0',
    ['.zip', '.zipx', '.7z', '.rar', '.tar', '.gz', '.tgz'],
    ['import', 'export', 'validate'],
    'Archive listing, search, checksum, and extraction policy reference; use only through isolated archive worker boundaries.',
  ),
  source(
    'nanazip',
    'https://github.com/M2Team/NanaZip',
    'NanaZip',
    'document',
    'selected_external_process',
    'active',
    null,
    ['.zip', '.7z', '.rar', '.tar'],
    ['import', 'export', 'validate'],
    'Smart extraction, hash, and modern archive UI reference; production route stays behind a worker/service adapter.',
  ),
  source(
    'peazip-translations',
    'https://github.com/peazip/PeaZip-Translations',
    'PeaZip translations',
    'document',
    'reference_only',
    'active',
    null,
    ['.zip', '.7z', '.rar'],
    ['viewer'],
    'Archive terminology/i18n reference for package inspection UI.',
  ),
  source(
    'stirling-pdf',
    'https://github.com/Stirling-Tools/Stirling-PDF',
    'Stirling PDF',
    'document',
    'selected_external_process',
    'active',
    'MIT',
    ['.pdf', '.pdfa'],
    ['import', 'export', 'online_edit', 'ocr', 'document_conversion'],
    'Priority PDF service adapter for split, merge, OCR, conversion, and derivative jobs.',
  ),
  source(
    'pdfjs',
    'https://github.com/mozilla/pdf.js',
    'PDF.js',
    'document',
    'selected',
    'active',
    'Apache-2.0',
    ['.pdf'],
    ['viewer'],
    'Browser PDF rendering route only; editing and OCR stay in workers/services.',
  ),
  source(
    'mupdf',
    'https://github.com/ArtifexSoftware/mupdf',
    'MuPDF',
    'document',
    'selected_external_process',
    'active',
    'AGPL-3.0/commercial',
    ['.pdf', '.xps', '.epub'],
    ['import', 'export', 'document_conversion'],
    'Use mutool as an external process or through commercial licensing; do not link AGPL library into core.',
  ),
  source(
    'paddleocr',
    'https://github.com/PaddlePaddle/PaddleOCR',
    'PaddleOCR',
    'document',
    'selected',
    'active',
    'Apache-2.0',
    ['.pdf', '.png', '.jpg', '.jpeg', '.webp', '.heic'],
    ['ocr', 'document_conversion'],
    'Priority OCR worker dependency for documents and images.',
  ),
  source(
    'unstructured',
    'https://github.com/Unstructured-IO/unstructured',
    'Unstructured',
    'document',
    'selected_external_process',
    'active',
    'Apache-2.0',
    ['.pdf', '.docx', '.pptx', '.xlsx', '.html'],
    ['import', 'document_conversion'],
    'Broad document parsing fallback through isolated worker/service packaging when Docling/MinerU/MarkItDown are insufficient.',
  ),
  source(
    'marker',
    'https://github.com/VikParuchuri/marker',
    'Marker',
    'document',
    'selected_external_process',
    'active',
    'GPL-3.0',
    ['.pdf'],
    ['import', 'ocr', 'document_conversion'],
    'High-quality PDF-to-Markdown candidate, but GPL keeps it behind an isolated service/process boundary.',
  ),
  source(
    'markitdown',
    'https://github.com/microsoft/markitdown',
    'Microsoft MarkItDown',
    'document',
    'selected',
    'active',
    'MIT',
    ['.doc', '.docx', '.ppt', '.pptx', '.xls', '.xlsx', '.pdf'],
    ['import', 'document_conversion'],
    'Priority Office/PDF/media-to-Markdown extraction worker.',
  ),
  source(
    'collabora-online',
    'https://github.com/CollaboraOnline/online',
    'Collabora Online',
    'office',
    'selected_external_process',
    'active',
    'MPL-2.0',
    ['.doc', '.docx', '.odt', '.xlsx', '.ods', '.pptx', '.odp'],
    ['online_edit', 'document_conversion'],
    'Best-fit self-hosted Office editor candidate through WOPI/service isolation, not embedded in core.',
  ),
  source(
    'onlyoffice-documentserver',
    'https://github.com/ONLYOFFICE/DocumentServer',
    'ONLYOFFICE DocumentServer',
    'office',
    'selected_external_process',
    'active',
    'AGPL-3.0',
    ['.doc', '.docx', '.xlsx', '.pptx'],
    ['online_edit', 'document_conversion'],
    'Office editing fallback only as an isolated service or commercial deployment because of AGPL.',
  ),
  source(
    'excelize',
    'https://github.com/qax-os/excelize',
    'Excelize',
    'document',
    'selected',
    'active',
    'BSD-3-Clause',
    ['.xls', '.xlsx', '.xlsm', '.xlsb'],
    ['import', 'export', 'online_edit', 'ai_generate'],
    'Priority spreadsheet read/write/generation sidecar route.',
  ),
  source(
    'ffmpeg',
    'https://github.com/FFmpeg/FFmpeg',
    'FFmpeg',
    'media',
    'selected_external_process',
    'active',
    'LGPL/GPL depending on build',
    ['.mp4', '.webm', '.mov', '.mkv', '.avi', '.wav', '.mp3', '.m4a', '.flac', '.ogg', '.webp', '.gif'],
    ['import', 'export'],
    'Selected media transcode engine through external-process worker isolation.',
  ),
  source(
    'opencv',
    'https://github.com/opencv/opencv',
    'OpenCV',
    'image',
    'selected',
    'active',
    'Apache-2.0',
    ['.png', '.jpg', '.jpeg', '.webp', '.tif', '.tiff'],
    ['import', 'document_conversion'],
    'Selected image analysis and computer-vision worker dependency.',
  ),
  source(
    'imagemagick',
    'https://github.com/ImageMagick/ImageMagick',
    'ImageMagick',
    'image',
    'selected_external_process',
    'active',
    'ImageMagick',
    ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.tif', '.tiff', '.avif'],
    ['import', 'export'],
    'Selected image derivative engine through external-process worker isolation.',
  ),
  source(
    'sharp',
    'https://github.com/lovell/sharp',
    'Sharp/libvips',
    'image',
    'selected',
    'active',
    'Apache-2.0',
    ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.avif', '.svg'],
    ['import', 'export'],
    'Preferred Node/Next image pipeline dependency where server-side JavaScript image transforms are required.',
  ),
  source(
    'gdal',
    'https://github.com/OSGeo/gdal',
    'GDAL/OGR',
    'gis',
    'selected_external_process',
    'active',
    'MIT/X-style',
    ['.geojson', '.gpkg', '.shp', '.kml', '.gml'],
    ['import', 'export'],
    'Selected GIS conversion/indexing engine through ogr2ogr external-process isolation.',
  ),
  source(
    'pdal',
    'https://github.com/PDAL/PDAL',
    'PDAL',
    'gis',
    'selected_external_process',
    'active',
    'BSD-3-Clause',
    ['.las', '.laz', '.e57', '.ply'],
    ['import', 'export'],
    'Selected point-cloud metadata and conversion route through external-process isolation.',
  ),
  source(
    'maplibre-gl-js',
    'https://github.com/maplibre/maplibre-gl-js',
    'MapLibre GL JS',
    'gis',
    'selected',
    'active',
    'BSD-3-Clause',
    ['.geojson', '.mvt'],
    ['viewer'],
    'Preferred open-source web map renderer for vector tiles and 2D/2.5D GIS views.',
  ),
] as const satisfies readonly AdapterSource[];

export const formatAdapterRequirements = [
  requirement(
    'pdf',
    ['.pdf', '.pdfa'],
    ['browser PDF viewer', 'Docling worker', 'Stirling PDF service', 'PaddleOCR worker'],
    ['pdfjs', 'docling', 'stirling-pdf', 'paddleocr', 'markitdown', 'mupdf', 'marker', 'unstructured'],
    'direct_browser',
    'service',
    'provider',
    'service',
    'available',
  ),
  requirement(
    'image',
    ['.png', '.jpg', '.jpeg', '.svg', '.webp', '.gif', '.heic'],
    ['browser image viewer', 'OpenCV worker', 'ImageMagick worker', 'PaddleOCR worker', 'image generation provider'],
    ['opencv', 'imagemagick', 'sharp', 'paddleocr'],
    'direct_browser',
    'worker',
    'provider',
    'worker',
    'available',
  ),
  requirement(
    'video',
    ['.mp4', '.webm', '.mov', '.mkv', '.avi'],
    ['browser video viewer', 'transcode worker', 'video generation provider'],
    ['ffmpeg', 'blender', 'blender-mcp'],
    'direct_browser',
    'worker',
    'provider',
    'worker',
    'available',
  ),
  requirement(
    'voice',
    ['.wav', '.mp3', '.m4a', '.flac', '.ogg', '.aac'],
    ['browser audio viewer', 'ASR/TTS provider', 'audio worker'],
    ['ffmpeg', 'markitdown'],
    'direct_browser',
    'worker',
    'provider',
    'worker',
    'available',
  ),
  requirement(
    'office-document',
    ['.doc', '.docx', '.odt', '.rtf', '.ppt', '.pptx', '.odp'],
    [
      'LibreOffice preview',
      'Docling worker',
      'MarkItDown worker',
      'Collabora WOPI service',
      'Univer editing service',
      'template generation worker',
    ],
    ['docling', 'markitdown', 'collabora-online', 'onlyoffice-documentserver', 'dream-num-univer'],
    'worker',
    'worker',
    'provider',
    'worker',
    'adapter_required',
  ),
  requirement(
    'spreadsheet',
    ['.xls', '.xlsx', '.xlsm', '.xlsb', '.ods'],
    [
      'LibreOffice preview',
      'Docling worker',
      'Excelize sidecar',
      'Collabora WOPI service',
      'Univer Sheets editing service',
      'schema generation worker',
    ],
    ['docling', 'excelize', 'markitdown', 'collabora-online', 'onlyoffice-documentserver', 'dream-num-univer', 'speckle-excel'],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'openbim',
    ['.ifc', '.ifczip', '.ids', '.bcf', '.bcfzip', '.idm'],
    [
      'buildingSMART contract',
      'IDM exchange requirement manifest',
      'web-ifc browser runtime',
      'IfcOpenShell worker',
      'bSDD classification enrichment',
      'BCF issue package parser',
      'buildingSMART validate/IDS audit',
    ],
    [
      'buildingsmart',
      'buildingsmart-idm',
      'buildingsmart-bsdd',
      'buildingsmart-ids',
      'buildingsmart-bcf-api',
      'buildingsmart-bcf-xml',
      'thatopen-engine-web-ifc',
      'thatopen-web-ifc-three',
      'ifc-lite',
      'ifcopenshell',
      'buildingsmart-validate',
      'buildingsmart-ids-audit',
    ],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'revit-autodesk',
    ['.rvt', '.rfa'],
    ['Autodesk APS/Revit adapter', 'Revit MCP bridge'],
    ['autodesk', 'revit-mcp-server', 'revit-text-to-braille'],
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_adapter_required',
  ),
  requirement(
    'tekla-trimble',
    ['.tekla'],
    ['Tekla Structures Open API adapter', 'Trimble Connect adapter'],
    [
      'trimble-solutions',
      'tekla-structures-open-api',
      'tekla-open-api-overview',
    ],
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_adapter_required',
  ),
  requirement(
    'rhino-grasshopper',
    ['.3dm', '.gh', '.ghx'],
    ['Rhino/Grasshopper licensed sidecar', 'Speckle Rhino exporter'],
    [
      'mcneel',
      'speckle-ifc-exporter-rhino',
      'speckle-ifc-exporter-grasshopper',
    ],
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_adapter_required',
  ),
  requirement(
    'cad-drawing',
    ['.dwg', '.dxf'],
    ['licensed DWG adapter', 'DXF parser worker', 'Autodesk APS boundary'],
    ['autodesk', 'libredwg', 'threejs'],
    'worker',
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_adapter_required',
  ),
  requirement(
    'cad-kernel',
    ['.step', '.stp', '.iges', '.igs', '.brep'],
    ['ForgeCAD generation/export worker', 'OCCT worker', 'OCP Python binding', 'build123d generation worker', 'CadQuery generation worker', 'FreeCAD headless worker'],
    ['forgecad', 'occt', 'ocp', 'build123d', 'cadquery', 'freecad', 'text-to-cad', 'cadam'],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'mesh-scene',
    ['.glb', '.gltf', '.stl', '.obj', '.fbx', '.skp'],
    ['Three.js viewer', 'Blender service', 'mesh conversion worker'],
    [
      'threejs',
      'react-three-fiber',
      'babylonjs-engine',
      'blender',
      'blender-mcp',
      'speckle-blender',
      'pascal-editor',
    ],
    'direct_browser',
    'worker',
    'worker',
    'worker',
    'available',
  ),
  requirement(
    'blender-scene',
    ['.blend'],
    ['Blender external process', 'Blender MCP bridge', 'mesh export worker'],
    ['blender', 'blender-mcp', 'speckle-blender'],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'bim-automation',
    ['.dyn'],
    ['Dynamo licensed runtime', 'Dynamo/Revit automation bridge'],
    ['dynamo', 'dynamo-text', 'revit-text-to-braille'],
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_service',
    'licensed_adapter_required',
  ),
  requirement(
    'cnc-machine',
    ['.nc'],
    ['CNC/G-code parser worker', 'production routing adapter'],
    ['occt'],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'point-cloud-reality',
    ['.e57', '.las', '.ply', '.spz'],
    [
      'point-cloud worker',
      '3D Tiles worker',
      'Cesium viewer',
      'Gaussian Splatting worker',
    ],
    ['pdal', 'gdal', '3d-tiles-renderer-js', 'cesium', 'maplibre-gl-js', 'threejs', 'blender', 'blender-mcp'],
    'worker',
    'worker',
    'worker',
    'worker',
    'adapter_required',
  ),
  requirement(
    'gantt-flow-mindmap',
    ['.mermaid', '.mmd', '.json'],
    [
      'typed graph/schema worker',
      'Mermaid/SVG/PDF exporter',
      'AntV G6/G2',
      'Plotly.js',
    ],
    ['markitdown', 'antvis', 'antvis-g2', 'antvis-g6', 'plotly-js'],
    'direct_browser',
    'worker',
    'provider',
    'worker',
    'adapter_required',
  ),
] as const satisfies readonly FormatAdapterRequirement[];

function source(
  id: AdapterSource['id'],
  url: AdapterSource['url'],
  label: AdapterSource['label'],
  category: AdapterSource['category'],
  decision: AdapterSource['decision'],
  state: AdapterSource['state'],
  license: AdapterSource['license'],
  formats: AdapterSource['formats'],
  capabilities: AdapterSource['capabilities'],
  note: AdapterSource['note'],
): AdapterSource {
  return {
    id,
    url,
    label,
    category,
    decision,
    state,
    license,
    formats,
    capabilities,
    note,
  };
}

function requirement(
  family: FormatAdapterRequirement['family'],
  extensions: FormatAdapterRequirement['extensions'],
  adapters: FormatAdapterRequirement['adapters'],
  sourceIds: FormatAdapterRequirement['sourceIds'],
  importRoute: FormatAdapterRequirement['importRoute'],
  onlineEditRoute: FormatAdapterRequirement['onlineEditRoute'],
  aiGenerationRoute: FormatAdapterRequirement['aiGenerationRoute'],
  exportRoute: FormatAdapterRequirement['exportRoute'],
  status: FormatAdapterRequirement['status'],
): FormatAdapterRequirement {
  return {
    family,
    extensions,
    adapters,
    sourceIds,
    importRoute,
    onlineEditRoute,
    aiGenerationRoute,
    exportRoute,
    status,
  };
}

export function adapterSourceByUrl(url: string): AdapterSource | undefined {
  return adapterSourceRegistry.find((source) => source.url === url);
}

export function adapterSourceById(id: string): AdapterSource | undefined {
  return adapterSourceRegistry.find((source) => source.id === id);
}

export function normalizeAdapterExtension(value: string): string {
  const trimmed = value.trim().toLowerCase();
  if (!trimmed) return '';
  if (trimmed.startsWith('.')) return trimmed;
  const dot = trimmed.lastIndexOf('.');
  return dot >= 0 ? trimmed.slice(dot) : `.${trimmed}`;
}

export function adapterRequirementForExtension(
  extension: string,
): FormatAdapterRequirement | undefined {
  const ext = normalizeAdapterExtension(extension);
  return formatAdapterRequirements.find((requirement) =>
    requirement.extensions.includes(ext),
  );
}

export function requiredAdaptersForFileName(
  fileName: string,
  mimeType?: string,
): readonly string[] {
  const requirement = adapterRequirementForExtension(fileName);
  if (requirement) return requirement.adapters;

  const mime = mimeType?.toLowerCase() ?? '';
  if (mime.startsWith('image/')) {
    return ['browser image viewer', 'OpenCV worker', 'ImageMagick worker', 'PaddleOCR worker'];
  }
  if (mime.startsWith('video/')) {
    return ['browser video viewer', 'FFmpeg transcode worker'];
  }
  if (mime.startsWith('audio/')) {
    return ['browser audio viewer', 'FFmpeg transcode worker', 'ASR/TTS provider'];
  }
  if (mime === 'application/pdf') {
    return ['browser PDF viewer', 'Docling worker', 'Stirling PDF service'];
  }

  return ['registered parser/viewer worker'];
}

export function adapterSourcesForFileName(fileName: string): AdapterSource[] {
  const requirement = adapterRequirementForExtension(fileName);
  if (!requirement) return [];

  return requirement.sourceIds
    .map(adapterSourceById)
    .filter((source): source is AdapterSource => Boolean(source));
}
