// lib/module-operations.ts - Interactive module workbench fixtures
// License: Apache-2.0

import type { ModuleId } from "./module-registry";

export interface ModuleFeatureCard {
  id: string;
  title: string;
  description: string;
  owner: string;
  status: "ready" | "running" | "review" | "blocked";
  metrics: string[];
}

export interface ModuleOperationButton {
  id: string;
  label: string;
  result: string;
}

export interface ModuleOperationalProfile {
  moduleId: ModuleId;
  title: string;
  subtitle: string;
  summary?: string;
  description?: string;
  features: ModuleFeatureCard[];
  operations: ModuleOperationButton[];
  statusTracks: string[];
}

function feature(
  id: string,
  title: string,
  description: string,
  owner: string,
  status: ModuleFeatureCard["status"],
  metrics: string[],
): ModuleFeatureCard {
  return { id, title, description, owner, status, metrics };
}

function operation(
  id: string,
  label: string,
  result: string,
): ModuleOperationButton {
  return { id, label, result };
}

export const moduleOperationalProfiles: Partial<
  Record<ModuleId, ModuleOperationalProfile>
> = {
  planning_management: {
    moduleId: "planning_management",
    title: "项目计划与全周期履约工作台",
    subtitle:
      "Project Planning Studio: 把立项、WBS、进度、资源、风险、RACI、图表模板、审批和交付里程碑连接到生产与施工节拍。",
    features: [
      feature(
        "project-initiation",
        "立项资料",
        "项目范围、合同边界、法域、业主要求和交付标准。",
        "项目经理",
        "running",
        ["完整 86%", "待补 9 项", "风险 4 条"],
      ),
      feature(
        "wbs",
        "WBS",
        "按设计、采购、生产、物流、施工、验收拆解到可执行任务包。",
        "计划工程师",
        "ready",
        ["任务 186 个", "关键 23 个", "挂接率 92%"],
      ),
      feature(
        "planning-studio",
        "Project Planning Studio",
        "甘特、WBS、PERT、RACI、看板、风险矩阵、资源负荷和 Mermaid/BPMN 导出。",
        "计划工程师",
        "running",
        ["模板 50+ 个", "CDE 归档", "AI顾问"],
      ),
      feature(
        "progress-feedback",
        "进度反馈",
        "按任务登记实际进度、完成、阻断、反馈证据和状态更新。",
        "计划工程师",
        "running",
        ["反馈 2 条", "待复核 3 项", "SPI 0.31"],
      ),
      feature(
        "schedule-warning",
        "进度预警",
        "基于计划应达、实际反馈、临期、逾期、阻断、资源和风险生成预警。",
        "项目控制经理",
        "review",
        ["预警 8 条", "逾期 3 项", "高风险 2 条"],
      ),
      feature(
        "schedule-adjustment",
        "进度调整",
        "按任务窗口顺延/提前,可联动后续依赖任务和里程碑。",
        "计划经理",
        "review",
        ["调整 0 次", "依赖联动", "审批留痕"],
      ),
      feature(
        "baseline-schedule",
        "基线进度",
        "总控、专项、周计划和 4D 进度基线。",
        "计划经理",
        "review",
        ["基线 1 版", "偏差 -2.5 天", "关键路径 4 条"],
      ),
      feature(
        "resource-plan",
        "资源计划",
        "人机料、产线、车辆、吊装窗口和现金流约束。",
        "资源经理",
        "running",
        ["资源 7 类", "冲突 3 个", "负载 84%"],
      ),
      feature(
        "risk-register",
        "风险清单",
        "设计变更、供应、制造、运输、吊装、安全和合规风险。",
        "项目总工",
        "running",
        ["风险 31 条", "高风险 5 条", "闭环 58%"],
      ),
      feature(
        "approval-log",
        "审批记录",
        "立项、方案、清单、采购、工单、施工和结算审批链。",
        "文控经理",
        "ready",
        ["审批 42 条", "待审 6 条", "逾期 1 条"],
      ),
    ],
    operations: [
      operation(
        "generate-wbs",
        "生成 WBS",
        "已按 14 模块生成 WBS、责任人和关键路径。",
      ),
      operation(
        "open-planning-studio",
        "打开 Project Planning Studio",
        "已进入在线计划图表编制、保存版本、审批归档和导出闭环。",
      ),
      operation(
        "baseline-schedule",
        "生成基线计划",
        "已生成总控计划、周计划和里程碑看板。",
      ),
      operation(
        "record-progress-feedback",
        "登记进度反馈",
        "已登记任务实际进度、任务状态和 CDE 反馈证据。",
      ),
      operation(
        "run-schedule-warning",
        "运行进度预警",
        "已基于 SPI、逾期、临期、阻断、资源和风险生成预警。",
      ),
      operation(
        "adjust-schedule-window",
        "调整计划窗口",
        "已生成顺延/提前任务窗口并联动后续依赖任务。",
      ),
      operation(
        "evaluate-risk",
        "评估履约风险",
        "已输出供应、制造、施工和资金风险矩阵。",
      ),
      operation(
        "sync-downstream",
        "同步下游模块",
        "已把计划基线同步到设计、采购、生产和施工模块。",
      ),
    ],
    statusTracks: [
      "立项",
      "WBS",
      "基线计划",
      "进度反馈",
      "进度预警",
      "计划调整",
      "任务状态",
      "履约闭环",
    ],
  },
  marketing_service: {
    moduleId: "marketing_service",
    title: "造房网60天市场推广执行工作台",
    subtitle:
      "线上冷启动挖掘0号合伙人、线下合伙人破局、合伙人赋能、口碑引爆、样板房成交和裂变复盘。",
    features: [
      feature(
        "landing-page",
        "官网/落地页8项收口",
        "主标题、样板房图视频、核心优势、流程拆解、合伙人政策、本地案例、企微二维码和预约入口。",
        "增长负责人",
        "running",
        ["8项内容", "3城乡镇", "样板房1处"],
      ),
      feature(
        "wechat-sop",
        "企业微信承接SOP",
        "自动欢迎语、避坑手册、样板房视频、本地政策摘要、预约系统和客户标签。",
        "企微顾问",
        "ready",
        ["24h响应", "标签4类", "预约同步"],
      ),
      feature(
        "zero-partner",
        "0号合伙人筛选",
        "官网停留3分钟、主动咨询合作、主动加微且响应积极，优先本地资源和公信力。",
        "合伙人经理",
        "review",
        ["每城≥1个", "2-3个种子", "低质剔除"],
      ),
      feature(
        "partner-network",
        "10-15个合伙人网络",
        "设计机构、包工头/施工队、同乡会/商会负责人、乡村意见领袖。",
        "渠道负责人",
        "running",
        ["每城3-5个", "4类资源", "服务群"],
      ),
      feature(
        "sample-house-close",
        "样板房10步转化",
        "实景参观、AR透视、触摸型材、数据对比、工期讲解、政策解读、预算测算、案例播放、签约。",
        "样板房接待",
        "ready",
        ["2人接待", "10步流程", "周末集中"],
      ),
      feature(
        "case-spread",
        "标杆案例传播",
        "1-2个本地标杆客户，开工到完工全程拍摄，合伙人每周转发2-3次。",
        "内容运营",
        "running",
        ["1-2分钟视频", "5类圈层", "转发监督"],
      ),
    ],
    operations: [
      operation(
        "build-partner-funnel",
        "生成合伙人漏斗",
        "已按官网停留、合作咨询、加微响应和本地资源筛选0号合伙人。",
      ),
      operation(
        "create-wechat-sop",
        "生成企微承接SOP",
        "已生成欢迎语、自动回复、预约提醒和客户标签字段。",
      ),
      operation(
        "issue-partner-kit",
        "发放合伙人工具包",
        "已生成合作手册、收益测算表、授权牌、二维码和转发文案模板。",
      ),
      operation(
        "plan-sample-house-day",
        "排周末样板房接待",
        "已按10步转化流程生成接待、测算、签约和跟进任务。",
      ),
    ],
    statusTracks: [
      "前期准备",
      "线上冷启动",
      "线下破局",
      "合伙人赋能",
      "口碑引爆",
      "样板房成交",
      "裂变复盘",
    ],
  },
  concept_design: {
    moduleId: "concept_design",
    title: "方案设计与概念生成工作台",
    subtitle: "从场地、需求和标准库生成多方案、指标分析、初步模型和展示包。",
    features: [
      feature(
        "site-condition",
        "场地条件",
        "用地边界、道路、吊装入口、周边风险和地勘资料。",
        "方案设计师",
        "running",
        ["红线 1 版", "出入口 3 个", "约束 12 条"],
      ),
      feature(
        "scheme-sketch",
        "方案草图",
        "平面、体量、柱网、功能流线和重钢结构策略。",
        "Generator Agent",
        "ready",
        ["草图 6 张", "体量 3 套", "柱网 2 档"],
      ),
      feature(
        "style-choice",
        "风格选型",
        "工业风、展示中心、厂房园区等风格和材料方向。",
        "视觉设计师",
        "ready",
        ["风格 5 类", "参考图 24 张", "视频脚本 2 版"],
      ),
      feature(
        "indicator-analysis",
        "指标分析",
        "面积、钢量、层高、造价、能耗和施工窗口快速评估。",
        "技术负责人",
        "review",
        ["钢量估算 92%", "成本偏差 8%", "规范预警 3 项"],
      ),
      feature(
        "initial-model",
        "初步模型",
        "生成可继续深化的 GLB/IFC 初步模型和构件编码草案。",
        "BIM 工程师",
        "running",
        ["GLB 1 个", "IFC 草案", "构件 186 件"],
      ),
    ],
    operations: [
      operation(
        "generate-scheme",
        "生成方案",
        "已生成三套概念方案和初步模型。",
      ),
      operation(
        "evaluate-code",
        "评估规范",
        "已按 GB/AISC/Eurocode/AS 做初筛预警。",
      ),
      operation(
        "create-presentation-pack",
        "生成展示包",
        "已生成客户展示 PDF、渲染图和短视频脚本。",
      ),
    ],
    statusTracks: [
      "场地录入",
      "多方案生成",
      "指标校核",
      "客户评审",
      "深化移交",
    ],
  },
  standard_library: {
    moduleId: "standard_library",
    title: "标准规范与族库治理工作台",
    subtitle: "统一管理规范、族库、样板、材质、图纸、模型、做法、规则和版本。",
    features: [
      feature(
        "standards",
        "标准规范",
        "中国、美国、欧洲、澳洲与企业标准条文、版本和法域映射，SJG 157 负责 BIM 语义字典类目。",
        "标准工程师",
        "review",
        ["SJG 157", "szbd RDF", "IFC 映射"],
      ),
      feature(
        "families",
        "族库构件",
        "重钢柱、梁、桁架、节点板、螺栓和机电支吊架族库。",
        "BIM 经理",
        "running",
        ["族 326 个", "属性完整 93%", "弃用 12 个"],
      ),
      feature(
        "templates",
        "样板文件",
        "项目模板、图纸模板、报价模板、BIM 模板和交付模板。",
        "文控经理",
        "ready",
        ["模板 42 个", "最新 38 个", "待发布 4 个"],
      ),
      feature(
        "materials",
        "材质库",
        "钢材、防腐、防火、焊材、高强螺栓和饰面材料。",
        "材料工程师",
        "ready",
        ["材料 218 项", "价格快照 3 版", "证书 96%"],
      ),
      feature(
        "drawings",
        "图纸",
        "标准图集、节点详图、CAD/PDF 来源和适用条件。",
        "设计管理员",
        "running",
        ["图纸 612 张", "节点 148 个", "差异 9 项"],
      ),
      feature(
        "models",
        "模型",
        "IFC、GLB、参数化构件和数字孪生基础模型。",
        "BIM 经理",
        "review",
        ["模型 84 个", "IFC4.3 62%", "GLB 91%"],
      ),
      feature(
        "methods",
        "做法库",
        "防火、防腐、屋面、围护、装配和施工工艺做法。",
        "工艺工程师",
        "ready",
        ["做法 73 项", "可制造 88%", "验收关联 64 项"],
      ),
      feature(
        "rules",
        "规则库",
        "结构、造价、施工、验收、安全和交付规则。",
        "规则工程师",
        "running",
        ["规则 392 条", "单测 86%", "阻断 5 条"],
      ),
      feature(
        "versions",
        "版本库",
        "规范、构件、做法、规则和企业知识版本链。",
        "架构师",
        "ready",
        ["版本 108 个", "回滚点 21 个", "发布候选 3 个"],
      ),
    ],
    operations: [
      operation(
        "search-code",
        "检索规范",
        "已返回适用条文、法域、版本风险和 SJG 157 语义类目。",
      ),
      operation(
        "generate-family",
        "生成族库",
        "已生成 Q355B 重钢构件族和属性集。",
      ),
      operation(
        "check-component",
        "校核构件",
        "已完成几何、属性、做法和规则库校核。",
      ),
      operation("publish-version", "发布版本", "已生成版本发布记录和回滚点。"),
    ],
    statusTracks: ["知识入库", "条文解析", "族库发布", "规则校核", "版本冻结"],
  },
  detailed_design: {
    moduleId: "detailed_design",
    title: "100间精品酒店 · 198份深化图纸工作台",
    subtitle:
      "Q235B全栓接重钢装配式，8大专项、33个分组、P1/P2/P3分阶段冻结，并提供平面生成、适配、家具布置和方案库复用。",
    features: [
      feature(
        "floor-plan-generate",
        "平面生成",
        "选择外边界、入口点和房间需求后生成多个可比较平面候选。",
        "深化设计师",
        "running",
        ["Generate", "多候选", "边界输入"],
      ),
      feature(
        "floor-plan-fit",
        "平面适配",
        "把既有住宅、套房或紧凑模板适配到当前边界并保留可调整参数。",
        "BIM 工程师",
        "review",
        ["Fit", "模板库", "边界复用"],
      ),
      feature(
        "floor-plan-furnish",
        "快速家具布置",
        "按房间类型放置床、沙发、餐桌、橱柜和卫浴，作为深化前的空间校验。",
        "室内深化设计师",
        "ready",
        ["Furnish", "家具层", "可隐藏"],
      ),
      feature(
        "ss-pack",
        "①重钢专项深化",
        "结构体系、全栓接节点、模块拆分和工厂加工图，钢构件下单前100%完成。",
        "重钢深化主师",
        "running",
        ["42份", "P1先行", "最高优先级"],
      ),
      feature(
        "ar-pack",
        "②建筑土建深化",
        "取消砌体承重和外墙抹灰，全部改为钢骨架围护、装配式地坪、预制钢梯和工厂天沟。",
        "建筑深化设计师",
        "review",
        ["25份", "钢构版", "P2同步"],
      ),
      feature(
        "id-pack",
        "③室内精装适配",
        "精装服从钢构模数、预埋前置、吊顶避梁、声桥切断和公差补偿。",
        "精装主案",
        "running",
        ["33份", "STC≥55", "IIC≥55"],
      ),
      feature(
        "mep-pack",
        "④机电综合改图",
        "管线沿梁侧排布，穿梁圆孔与SS-04-05一一对应，先BIM碰撞后下单。",
        "机电综合设计师",
        "running",
        ["30份", "零碰撞确认", "双签锁定"],
      ),
      feature(
        "env-fp-pack",
        "⑥⑦围护消防专项",
        "ALC、一体板、气密水密、热桥断桥、防火包覆、喷淋排烟避梁和防火分区。",
        "围护/消防顾问",
        "review",
        ["34份", "耐火极限", "气密线"],
      ),
      feature(
        "con-pack",
        "⑧现场装配工艺",
        "吊装、调平、螺栓紧固、拼缝防渗、样板间试装、QC和安全文明施工。",
        "现场钢构代表",
        "ready",
        ["18份", "CON-01~03", "验收签字"],
      ),
    ],
    operations: [
      operation(
        "register-drawing-catalog",
        "登记198份图纸目录",
        "已生成8大专项、33个分组和编号/阶段/岗位/优先级索引。",
      ),
      operation(
        "generate-floor-plan-options",
        "生成平面候选",
        "已根据外边界、入口和房间需求生成多套平面候选。",
      ),
      operation(
        "fit-floor-plan-template",
        "适配平面模板",
        "已把选定模板适配到当前边界并保留可调整参数。",
      ),
      operation(
        "furnish-floor-plan",
        "快速布置家具",
        "已按房间类型放置家具并输出空间预检提示。",
      ),
      operation(
        "freeze-p1-package",
        "冻结P1先行包",
        "已锁定55份P1图纸、螺栓孔位、耳板尺寸和预留孔洞。",
      ),
      operation(
        "sync-mep-holes",
        "同步穿梁孔位",
        "已校核SS-04-05与MEP-02-01/02-04的穿梁圆孔和双签记录。",
      ),
      operation(
        "run-hotel-clash-check",
        "运行酒店碰撞检查",
        "已生成MEP、消防、吊顶和钢构节点BCF闭环清单。",
      ),
    ],
    statusTracks: [
      "平面生成",
      "模板适配",
      "家具布置",
      "P1先行D1-D15",
      "P2同步D15-D60",
      "P3收口D40-D75",
      "孔位锁定",
      "制造移交",
      "施工工艺交底",
    ],
  },
  quantity_costing: {
    moduleId: "quantity_costing",
    title: "计量造价编审一体化工作台",
    subtitle:
      "按编制、审核、送审/审定对比、核增核减、费用/清单分析、审核报告和审定转预算组织完整造价工作流。",
    features: [
      feature(
        "project-tree",
        "项目结构树",
        "项目、单项、单位和专业工程层级,支持合并、替换、匹配、复制和软删除。",
        "造价工程师",
        "running",
        ["节点 4 个", "匹配 4 项", "待确认 1 项"],
      ),
      feature(
        "compile-bill",
        "编制",
        "工程概况、分部分项、措施项目、其他项目、费用汇总和报表。",
        "造价工程师",
        "review",
        ["清单 5 项", "费用汇总", "GB/T50500-2024"],
      ),
      feature(
        "review-version",
        "审核版本",
        "新建审核、导入审定、多版本管理、切换送审和审定转预算。",
        "注册造价工程师",
        "ready",
        ["第一审", "送审V1", "审定R1"],
      ),
      feature(
        "submitted-approved-compare",
        "送审/审定对比",
        "工程量差、综合单价差、综合合价差、增删改临标识和详细对比。",
        "造价工程师",
        "running",
        ["增 1 项", "删 1 项", "改 2 项"],
      ),
      feature(
        "increase-decrease",
        "核增核减",
        "核增有效、代码型核增、费用代号型核增、常数型核增和费用汇总累计。",
        "造价工程师",
        "ready",
        ["核增 36454", "核减 21840", "平衡校验"],
      ),
      feature(
        "analysis-report",
        "分析与报告",
        "费用分析、清单分析、批量勾选、过滤、合并、定位和审核报告。",
        "造价负责人",
        "review",
        ["费用分析", "清单分析", "报告草稿"],
      ),
    ],
    operations: [
      operation(
        "create-review",
        "新建审核",
        "已建立审核版本,送审和审定数据分别快照。",
      ),
      operation(
        "import-approved",
        "导入审定",
        "已导入审定数据并按单位工程名称完成匹配。",
      ),
      operation(
        "calculate-delta",
        "计算增减",
        "已计算工程量差、增减金额、核增和核减。",
      ),
      operation(
        "select-analysis",
        "批量勾选分析",
        "已按增减金额占比选择清单分析范围。",
      ),
      operation(
        "generate-review-report",
        "生成审核报告",
        "已生成待专业复核的审核报告草稿和 CDE 证据。",
      ),
    ],
    statusTracks: [
      "新建工程",
      "编制",
      "新建审核",
      "导入审定",
      "版本管理",
      "核增核减",
      "分析报告",
      "审定转预算",
    ],
  },
  material_logistics: {
    moduleId: "material_logistics",
    title: "酒店重钢构件材料物流与批次追踪工作台",
    subtitle:
      "承接SS-04-08 BOM、SS-04-11构件编码、模块运输加固和现场进场核对，组织采购、包装、装车、物流、签收和堆场。",
    features: [
      feature(
        "inventory",
        "材料库存",
        "钢材、焊材、涂料、高强螺栓和余料库存。",
        "仓储经理",
        "running",
        ["库存 82%", "红区 3 类", "锁定批次 12"],
      ),
      feature(
        "supplier",
        "供应商",
        "供应商资质、履约、价格、交期和风险画像。",
        "采购经理",
        "ready",
        ["供应商 46 家", "合格 39 家", "预警 4 家"],
      ),
      feature(
        "price",
        "价格",
        "区域、时间、规格、报价来源和价格有效期。",
        "采购经理",
        "review",
        ["报价 128 条", "过期 9 条", "波动 +4.1%"],
      ),
      feature(
        "rfq",
        "询价/比价",
        "RFQ、比价表、技术澄清和采购审批。",
        "采购专员",
        "running",
        ["RFQ 7 单", "待回 2 单", "推荐 3 家"],
      ),
      feature(
        "purchase-plan",
        "采购计划",
        "按 DDMRP 缓冲、生产节拍和施工窗口生成采购计划。",
        "计划工程师",
        "running",
        ["计划 5 批", "缺口 18t", "ETA 偏差 6h"],
      ),
      feature(
        "cutting-list",
        "下料单",
        "把 BOQ/BOM 转成可加工下料单和余料策略。",
        "工艺工程师",
        "ready",
        ["下料 312 条", "利用率 91%", "余料 4.8t"],
      ),
      feature(
        "production-bom",
        "加工 BOM",
        "构件、材料、工序、检测和包装关联。",
        "工艺工程师",
        "review",
        ["BOM 28 包", "缺字段 3 项", "冻结 11 包"],
      ),
      feature(
        "packing",
        "包装",
        "按构件号-方向-楼层-区域、吊装顺序、防护要求和二维码组织包装单元。",
        "物流经理",
        "ready",
        ["SS-04-11", "包装单元", "二维码"],
      ),
      feature(
        "loading",
        "装车",
        "按模块重心、运输限界宽≤3.9m/高≤4.5m、临时支撑和堆放支点安排装车。",
        "物流经理",
        "running",
        ["宽≤3.9m", "高≤4.5m", "支点校核"],
      ),
      feature(
        "delivery",
        "物流",
        "GPS、ETA、道路许可、异常和现场到货计划。",
        "调度员",
        "running",
        ["在途 9 车", "延误 1 车", "ETA 92%"],
      ),
      feature(
        "arrival",
        "到货",
        "到货验收、损伤照片、证书和现场堆放建议。",
        "现场材料员",
        "review",
        ["到货 41 包", "待验 8 包", "异常 2 项"],
      ),
      feature(
        "yard",
        "现场堆放",
        "堆场分区、吊装顺序、周转路线和占用率。",
        "施工总包",
        "running",
        ["堆场 73%", "冲突 2 项", "空位 11 个"],
      ),
      feature(
        "receipt",
        "签收",
        "签收人、时间、照片、批次和二维码证据。",
        "材料员",
        "ready",
        ["签收 33 包", "待签 8 包", "证据 96%"],
      ),
      feature(
        "batch-trace",
        "批次追踪",
        "炉批号、材质证明、二维码、RFID 和构件绑定。",
        "质保工程师",
        "running",
        ["追踪率 94%", "证书缺口 5", "RFID 88%"],
      ),
    ],
    operations: [
      operation(
        "generate-purchase-plan",
        "生成采购计划",
        "已生成采购批次、RFQ 和 DDMRP 缓冲建议。",
      ),
      operation(
        "generate-cutting-list",
        "生成下料单",
        "已生成下料单、余料策略和加工 BOM。",
      ),
      operation(
        "arrange-logistics",
        "安排物流",
        "已按构件编码、模块重心、运输限界和吊装顺序生成装车计划与ETA。",
      ),
      operation(
        "receive-batch",
        "签收批次",
        "已更新构件物料进场核对、损伤照片、证书和现场堆放分区。",
      ),
    ],
    statusTracks: [
      "BOM接收",
      "采购下单",
      "模块加固",
      "包装装车",
      "运输ETA",
      "到货签收",
      "堆场分区",
    ],
  },
  production_manufacturing: {
    moduleId: "production_manufacturing",
    title: "Q235B全栓接酒店构件生产工作台",
    subtitle:
      "按SS-04加工深化、孔位坐标、BOM、无现场焊接、防腐防火、构件编码和包装发运组织MES工单。",
    features: [
      feature(
        "p1-release",
        "P1下单闸门",
        "重钢专项图纸、螺栓孔位、耳板尺寸和预留孔洞未冻结不得进厂排产。",
        "生产负责人",
        "review",
        ["55份P1", "孔位锁定", "双签确认"],
      ),
      feature(
        "shop-drawing",
        "钢构件加工详图",
        "钢柱、主梁、次梁每型下料长度、端头铣平、孔位坐标、公差0~-2mm。",
        "制图专员",
        "running",
        ["SS-04-01~03", "0~-2mm", "圆孔"],
      ),
      feature(
        "hole-cnc",
        "孔位CNC数据",
        "全部构件孔位统一坐标系，孔径公差+0.5mm，穿梁圆孔与MEP锁定表一致。",
        "数控工程师",
        "running",
        ["SS-04-04", "SS-04-05", "CNC基础数据"],
      ),
      feature(
        "factory-weld",
        "仅工厂焊接",
        "端板、加劲肋、吊耳和节点板在工厂焊接，现场安装保持全栓接。",
        "焊接工程师",
        "ready",
        ["无现场焊接", "吊耳工厂焊", "WPS/PQR"],
      ),
      feature(
        "coating",
        "防腐防火涂装",
        "环氧富锌70μm、环氧云铁100μm、聚氨酯60μm，柱3h/梁2h/楼板1.5h。",
        "涂装工程师",
        "review",
        ["3层涂装", "耐火分区", "环境记录"],
      ),
      feature(
        "bom-code",
        "BOM与包装编码",
        "构件编号、规格、单重、数量、材质Q235B、出厂顺序和构件号-方向-楼层-区域喷涂。",
        "物料统筹人员",
        "running",
        ["SS-04-08", "SS-04-11", "二维码追溯"],
      ),
      feature(
        "factory-qc",
        "工厂质检放行",
        "尺寸、孔位、螺栓、涂装、防火和资料齐套后放行，异常进入返工闭环。",
        "质检工程师",
        "review",
        ["孔位抽检", "膜厚记录", "资料齐套"],
      ),
      feature(
        "schedule",
        "工厂排产",
        "产线负荷、班组、设备、瓶颈和换线策略。",
        "车间主任",
        "running",
        ["产线 4 条", "瓶颈 焊接", "节拍 92%"],
      ),
      feature(
        "mes-erp",
        "MES/ERP 对接",
        "工单、库存、成本、报工和质量数据同步。",
        "系统集成工程师",
        "ready",
        ["同步 97%", "失败 2 条", "延迟 14s"],
      ),
      feature(
        "paperclip-agent-control",
        "Paperclip Agent编排",
        "当前阶段部署 Paperclip v2026.517.0，把工厂任务、心跳、预算和审批回写到生产制造审计链。",
        "AI治理 / 生产负责人",
        "running",
        ["v2026.517.0", "Heartbeat", "预算硬停"],
      ),
      feature(
        "component-code",
        "构件编码",
        "二维码、RFID、IFC GUID、批次和工序证据绑定。",
        "质量管理员",
        "running",
        ["编码 2,418", "追溯 95%", "异常 7 件"],
      ),
      feature(
        "shipping",
        "包装发运",
        "包装、装车、出厂、签收和发运批次。",
        "物流经理",
        "ready",
        ["发运 9 批", "在途 3 批", "签收 6 批"],
      ),
      feature(
        "rework",
        "返工处理",
        "返工原因、责任、措施、复检和成本影响。",
        "质量经理",
        "review",
        ["返工 5 件", "闭环 2 件", "影响 1.6 天"],
      ),
    ],
    operations: [
      operation(
        "release-p1-production",
        "校核P1生产放行",
        "已检查55份P1图纸、孔位锁定和双签确认，未冻结项进入阻断。",
      ),
      operation(
        "generate-bolt-hole-cnc",
        "生成孔位CNC包",
        "已生成圆孔孔位CSV、NC/DXF和模型版本绑定。",
      ),
      operation(
        "generate-q235b-bom",
        "生成Q235B BOM",
        "已生成构件编号、规格、单重、材质、出厂顺序和包装单元。",
      ),
      operation(
        "run-coating-qc",
        "运行涂装质检",
        "已核对防腐膜厚、防火耐火极限和环境温湿度记录。",
      ),
      operation(
        "sync-paperclip-agent-board",
        "同步Paperclip编排面板",
        "已把工单、CNC、质检、发运任务同步到 Paperclip v2026.517.0，并写入 ArchIToken 审计事件。",
      ),
    ],
    statusTracks: [
      "P1放行",
      "加工详图",
      "孔位CNC",
      "工厂焊接",
      "防腐防火",
      "BOM编码",
      "包装发运",
      "Paperclip编排",
    ],
  },
  construction_management: {
    moduleId: "construction_management",
    title: "100间精品酒店现场装配施工工艺工作台",
    subtitle:
      "按CON-01~03组织吊装、调平、螺栓紧固、拼缝防渗、干湿分区、样板间试装、物料进场、QC、安全和竣工资料。",
    features: [
      feature(
        "hoisting",
        "吊装顺序",
        "柱→主梁→次梁→支撑，先内后外、先下后上，每步稳定性验算。",
        "现场钢构代表",
        "review",
        ["CON-01-01", "每日安装量", "塔吊覆盖"],
      ),
      feature(
        "leveling",
        "调平校准",
        "调平螺栓、柱顶水准仪测点、层间累积误差≤±5mm，每层复测。",
        "测量工程师",
        "running",
        ["CON-01-02", "≤±5mm", "每层复测"],
      ),
      feature(
        "bolt-torque",
        "高强螺栓紧固",
        "初拧50%→终拧100%，从中间向两端扩散，10%检验比例。",
        "栓接工艺顾问",
        "running",
        ["CON-01-03", "10%抽检", "扭矩标记"],
      ),
      feature(
        "seam-waterproof",
        "拼缝防渗隔声",
        "PU密封胶、48kg/m³矿棉、背衬板、内饰收口按不可逆工序执行。",
        "防水防渗顾问",
        "review",
        ["CON-01-04", "防水", "隔声"],
      ),
      feature(
        "dry-wet-zones",
        "干湿作业分区",
        "灌浆、打胶、防水湿作业区与干作业区隔离，控制穿插窗口。",
        "现场精装代表",
        "ready",
        ["CON-02-01", "穿插计划", "成品保护"],
      ),
      feature(
        "mockup-release",
        "样板间试装放行",
        "3间样板间端头转角问题清单修正后才能批量施工。",
        "项目总工",
        "blocked",
        ["3间样板间", "问题清单", "放行闸门"],
      ),
      feature(
        "daily-log",
        "日志",
        "施工日志、监理日志、旁站、天气和人机料。",
        "监理工程师",
        "ready",
        ["今日 3 篇", "自动摘要 1 篇", "缺签 2 人"],
      ),
      feature(
        "ar",
        "AR",
        "AR 安装定位、构件复核和现场指引。",
        "现场工程师",
        "ready",
        ["AR 点 24 个", "偏差 3 个", "通过 88%"],
      ),
      feature(
        "panorama",
        "360 全景",
        "全景巡检、进度影像和问题定位。",
        "资料员",
        "running",
        ["全景 118 张", "覆盖 91%", "新增 12 张"],
      ),
      feature(
        "scan3d",
        "三维扫描",
        "LiDAR/E57、控制点、残差和偏差热图。",
        "测量工程师",
        "review",
        ["扫描 9 批", "残差 26mm", "待复测 2 区"],
      ),
      feature(
        "oblique",
        "倾斜摄影",
        "无人机航线、倾斜模型和土建/钢构对齐。",
        "无人机飞手",
        "ready",
        ["航线 6 条", "点位 1,920", "精度 3cm"],
      ),
      feature(
        "drone",
        "无人机",
        "巡检、拍摄、吊装路径和安全监测。",
        "无人机飞手",
        "running",
        ["飞行 4 次", "异常 1 条", "电量 72%"],
      ),
      feature(
        "robot",
        "建筑机器人",
        "巡检机器人、喷涂/测量设备和自动记录。",
        "智能建造工程师",
        "ready",
        ["机器人 2 台", "任务 7 个", "在线 1 台"],
      ),
      feature(
        "iot",
        "IoT",
        "应力、风速、温湿度、设备和人员定位。",
        "IoT 工程师",
        "running",
        ["点位 86 个", "告警 4 条", "在线 94%"],
      ),
      feature(
        "visual-compare",
        "影像对比",
        "模型、计划、全景、点云和现场图像对比。",
        "BIM 工程师",
        "review",
        ["对比 32 组", "偏差 7 项", "阻断 2 项"],
      ),
      feature(
        "rectification",
        "整改闭环",
        "整改单、责任人、期限、复验和归档。",
        "总监理工程师",
        "running",
        ["整改单 11 个", "逾期 1 个", "闭环率 81%"],
      ),
      feature(
        "completion",
        "竣工资料",
        "验收、检测、签章、模型和归档清单。",
        "资料负责人",
        "ready",
        ["资料 76%", "缺项 18 个", "签章 63%"],
      ),
    ],
    operations: [
      operation(
        "generate-hoisting-plan",
        "生成吊装顺序",
        "已按柱、主梁、次梁、支撑生成安装顺序和稳定性检查点。",
      ),
      operation(
        "record-bolt-torque",
        "登记螺栓紧固",
        "已登记初拧、终拧、扭矩标记和10%抽检记录。",
      ),
      operation(
        "release-mockup-room",
        "样板间放行校核",
        "已生成3间样板间问题清单、修正方案和批量施工放行意见。",
      ),
      operation(
        "archive-completion",
        "归档竣工资料",
        "已生成竣工图、检验批、隐蔽验收、材料合格证和功能检测缺项清单。",
      ),
    ],
    statusTracks: [
      "吊装",
      "调平",
      "紧固",
      "拼缝",
      "干湿分区",
      "样板间",
      "QC安全",
      "竣工资料",
    ],
  },
  digital_twin: {
    moduleId: "digital_twin",
    title: "重钢结构数字孪生运行台",
    subtitle:
      "WebGPU/WGSL 原生主视口,融合 openBIM、glTF、3D Tiles、OpenUSD、3DGS/E57、IoT/SCADA 和 FEA/ROM。",
    features: [
      feature(
        "webgpu",
        "WebGPU 原生渲染状态",
        "检测 GPU Adapter、WGSL 渲染管线和帧率预算。",
        "图形工程师",
        "running",
        ["WebGPU ready", "WGSL pipeline", "GPU 72%"],
      ),
      feature(
        "three-fallback",
        "Three.js fallback 状态",
        "低能力设备自动切到 Three.js 兼容渲染。",
        "前端工程师",
        "ready",
        ["fallback idle", "兼容 96%", "降级 0 次"],
      ),
      feature(
        "assets",
        "IFC/GLB/3D Tiles/OpenUSD/3DGS/E57",
        "登记模型、地理空间、实景、点云、全景、扫描和倾斜摄影数据源。",
        "BIM 经理",
        "running",
        ["源 8 类", "对齐 87%", "缺口 3 项"],
      ),
      feature(
        "component-tree",
        "构件树",
        "Site / Building / Level / Zone / Element 可点击选择和回写。",
        "孪生工程师",
        "running",
        ["构件 2,418", "选中 1 件", "属性 91%"],
      ),
      feature(
        "layer-manager",
        "图层管理",
        "IFC、GLB、点云、360、三维扫描、倾斜摄影、进度、质量、安全、成本开关。",
        "项目经理",
        "ready",
        ["图层 12 个", "活动 7 个", "叠加 4 类"],
      ),
      feature(
        "progress-compare",
        "进度对比",
        "计划进度、实际安装、影像证据和 4D 回放。",
        "计划工程师",
        "review",
        ["完成 68%", "偏差 -2.5 天", "回放 12 帧"],
      ),
      feature(
        "overlays",
        "质量/安全/成本叠加图层",
        "缺陷、隐患、成本偏差和整改状态热力叠加。",
        "项目总工",
        "running",
        ["质量 9 项", "安全 6 项", "成本 +3.4%"],
      ),
      feature(
        "view-control",
        "视角切换",
        "总览、吊装、构件、点云残差和成本热区视角。",
        "现场工程师",
        "ready",
        ["视角 5 个", "收藏 3 个", "路径 1 条"],
      ),
      feature(
        "model-status",
        "模型状态",
        "模型版本、几何完整度、属性完整度和可编辑回写状态。",
        "BIM 经理",
        "review",
        ["版本 r42", "几何 94%", "属性 88%"],
      ),
      feature(
        "iot-status",
        "传感器/IoT 状态",
        "应力、应变、风速、扭矩、温度和安全点位。",
        "IoT 工程师",
        "running",
        ["点位 86", "告警 4", "在线 94%"],
      ),
    ],
    operations: [
      operation("toggle-layer", "切换图层", "已切换图层并记录视口状态。"),
      operation(
        "select-component",
        "选择构件",
        "已选择构件并显示几何、属性和风险。",
      ),
      operation("play-progress", "播放进度", "已启动 4D 进度对比回放。"),
      operation(
        "export-snapshot",
        "生成孪生快照",
        "已生成 Twin Snapshot 和证据包。",
      ),
      operation(
        "export-model-pack",
        "导出模型包",
        "已导出 IFC/GLB/SPZ/BCF 模型包清单。",
      ),
    ],
    statusTracks: ["渲染检测", "多源对齐", "构件选择", "图层叠加", "快照导出"],
  },
  digital_archive: {
    moduleId: "digital_archive",
    title: "数字档案与证据链工作台",
    subtitle:
      "项目档案、图纸模型、审批记录、日志、质量安全、竣工资料和版本链统一归档。",
    features: [
      feature(
        "project-archive",
        "项目档案",
        "合同、组织、计划、证据、交付物和项目元数据。",
        "资料负责人",
        "running",
        ["完整 82%", "缺项 18", "签章 63%"],
      ),
      feature(
        "drawing-archive",
        "图纸档案",
        "DWG/PDF/图集/节点详图版本链和签章。",
        "设计管理员",
        "review",
        ["图纸 146 张", "签章 89%", "缺版本 4 张"],
      ),
      feature(
        "model-archive",
        "模型档案",
        "IFC、GLB、STEP、SPZ 和模型版本差异。",
        "BIM 经理",
        "running",
        ["模型 24 个", "IFC 完整 95%", "SPZ 待审"],
      ),
      feature(
        "approval-record",
        "审批记录",
        "客户、设计、采购、生产、施工、竣工审批链。",
        "项目经理",
        "ready",
        ["审批 62 条", "待审 5 条", "驳回 1 条"],
      ),
      feature(
        "site-log",
        "施工日志",
        "施工日志、监理日志、旁站和天气人机料记录。",
        "监理工程师",
        "ready",
        ["日志 128 篇", "缺签 7 篇", "AI 摘要 81%"],
      ),
      feature(
        "quality-safety",
        "质量安全记录",
        "NCR、安全隐患、检测报告、整改闭环和复验。",
        "质量安全负责人",
        "review",
        ["记录 286 条", "开放 12 条", "闭环 88%"],
      ),
      feature(
        "completion-docs",
        "竣工资料",
        "验收、检测、签章、移交和长期保留策略。",
        "资料负责人",
        "running",
        ["归档 76%", "缺项 18", "移交包 1 个"],
      ),
      feature(
        "version-chain",
        "版本链",
        "文件哈希、签章、版本、回滚点和保留期限。",
        "文控经理",
        "ready",
        ["版本 312 个", "哈希 100%", "回滚点 42"],
      ),
    ],
    operations: [
      operation(
        "generate-archive-pack",
        "生成归档包",
        "已生成归档目录、文件哈希和移交清单。",
      ),
      operation(
        "validate-completeness",
        "校验完整性",
        "已校验签章、版本链和缺项清单。",
      ),
      operation(
        "export-archive",
        "导出档案",
        "已导出竣工档案包和长期保留索引。",
      ),
    ],
    statusTracks: ["收集", "校验", "签章", "封存", "移交"],
  },
  finance_hr: {
    moduleId: "finance_hr",
    title: "财务人力与项目经营工作台",
    subtitle:
      "合同台账、付款发票、成本台账、班组人员、考勤绩效、结算和经营分析统一联动。",
    features: [
      feature(
        "contract-ledger",
        "合同台账",
        "业主合同、分包合同、采购合同、补充协议和签章状态。",
        "合同经理",
        "running",
        ["合同 38 份", "待签 4 份", "风险 6 条"],
      ),
      feature(
        "payment-invoice",
        "付款发票",
        "付款计划、发票、收款、应付、应收和现金流预测。",
        "财务经理",
        "review",
        ["应收 4,280 万", "应付 2,960 万", "逾期 3 笔"],
      ),
      feature(
        "cost-ledger",
        "成本台账",
        "材料、加工、物流、吊装、管理费、风险费和变更成本。",
        "成本经理",
        "running",
        ["目标成本 1.28 亿", "偏差 +3.4%", "冻结 1 版"],
      ),
      feature(
        "crew-labor",
        "人员班组",
        "设计、采购、工厂、施工、监理、分包和资质证书。",
        "人力经理",
        "ready",
        ["人员 126 人", "证书 94%", "缺口 8 人"],
      ),
      feature(
        "attendance",
        "考勤绩效",
        "工厂与现场考勤、产量、质量、安全和绩效。",
        "现场管理员",
        "running",
        ["出勤 92%", "异常 7 条", "绩效 86%"],
      ),
      feature(
        "settlement",
        "结算归档",
        "进度款、签证、索赔、结算审核、档案和审计追溯。",
        "商务经理",
        "review",
        ["结算 63%", "签证 11 条", "待审 5 项"],
      ),
    ],
    operations: [
      operation(
        "forecast-cashflow",
        "预测现金流",
        "已生成回款、付款和资金缺口预测。",
      ),
      operation(
        "reconcile-cost",
        "核对成本",
        "已核对 BOQ、采购、生产和施工成本差异。",
      ),
      operation(
        "generate-settlement",
        "生成结算包",
        "已生成结算清单、签证索赔和审计索引。",
      ),
    ],
    statusTracks: ["合同", "付款", "成本", "人力", "绩效", "结算"],
  },
  ai_center: {
    moduleId: "ai_center",
    title: "企业级 AI 中心与智能体编排工作台",
    subtitle:
      "统一管理模型供应商、API 网关、RAG 知识库、MCP 工具、Agent 编排、OpenClaw 自动化、安全审计与成本策略。",
    features: [
      feature(
        "model-providers",
        "模型供应商",
        "Hugging Face、LM Studio、OpenRouter、OpenAI、Anthropic、Google等统一接入。",
        "AI 平台工程师",
        "running",
        ["供应商 10 个", "健康 96%", "fallback 2 条"],
      ),
      feature(
        "api-gateway",
        "AI API 网关",
        "统一鉴权、限流、路由、模型选择、流式输出、重试和降级策略。",
        "平台工程师",
        "ready",
        ["路由 18 条", "P95 420ms", "错误率 0.8%"],
      ),
      feature(
        "interface-management",
        "接口管理",
        "统一登记内部 Gateway、OpenAPI、OpenClaw、RAG 和 MCP 工具接口合同、鉴权边界和审计字段。",
        "平台集成工程师",
        "ready",
        ["合同注册", "权限边界", "审计绑定"],
      ),
      feature(
        "database-management",
        "数据库管理",
        "管理 AI 调用账本、运行时执行、RAG 来源、工具权限、成本事件和审计日志的数据对象。",
        "数据平台管理员",
        "review",
        ["RLS 边界", "生命周期", "迁移审查"],
      ),
      feature(
        "visualization-panels",
        "可视化面板",
        "发布模型路由拓扑、RAG 检索质量、MCP 工具调用、安全审计和成本治理运行视图。",
        "AI 运营负责人",
        "ready",
        ["拓扑图", "权限矩阵", "成本视图"],
      ),
      feature(
        "rag-knowledge",
        "RAG 知识库",
        "规范、合同、图纸、BIM 属性、审计记录和项目文档向量化检索。",
        "知识工程师",
        "running",
        ["知识库 12 个", "文档 18k", "命中率 87%"],
      ),
      feature(
        "mcp-tools",
        "MCP 工具注册",
        "把文件系统、模型仓库、数据库、审批流、造价表和 CDE 工具注册给智能体调用。",
        "工具链工程师",
        "review",
        ["工具 36 个", "启用 29 个", "待授权 4 个"],
      ),
      feature(
        "agent-orchestration",
        "Agent 编排",
        "Planner、Generator、Evaluator、Approver、Auditor 多智能体协同执行工程任务。",
        "Agent 架构师",
        "running",
        ["Agent 14 个", "工作流 9 条", "成功率 91%"],
      ),
      feature(
        "openclaw-automation",
        "OpenClaw 自动化",
        "面向工程任务的自动执行、回放、失败恢复、人工接管和操作审计。",
        "自动化负责人",
        "ready",
        ["任务 128 个", "自动化率 72%", "回滚点 31"],
      ),
      feature(
        "safety-audit",
        "安全审计",
        "提示词注入防护、敏感数据脱敏、权限边界、模型输出审查和追踪留痕。",
        "安全管理员",
        "review",
        ["策略 42 条", "阻断 7 次", "审计 100%"],
      ),
      feature(
        "cost-policy",
        "成本策略",
        "按租户、项目、模块、模型和任务统计 token 成本，并支持预算、告警和模型降级。",
        "FinOps 负责人",
        "running",
        ["本月 -18%", "预算 65%", "告警 3 条"],
      ),
    ],
    operations: [
      operation(
        "route-model",
        "生成模型路由建议",
        "已根据任务类型、成本预算和安全等级生成模型路由策略。",
      ),
      operation(
        "register-interface-contract",
        "登记接口合同",
        "已生成接口边界、鉴权方式、数据对象和审计字段。",
      ),
      operation(
        "review-database-binding",
        "审查数据库绑定",
        "已核对 AI 数据对象、RLS 边界、生命周期和迁移状态。",
      ),
      operation(
        "publish-visual-panel",
        "发布可视化面板",
        "已检查视图数据集、刷新策略、发布门禁和审计记录。",
      ),
      operation(
        "build-rag-index",
        "构建 RAG 索引",
        "已对规范、合同、图纸和审批记录构建检索索引。",
      ),
      operation(
        "register-mcp-tool",
        "注册 MCP 工具",
        "已生成工具 schema、权限边界和调用审计策略。",
      ),
      operation(
        "compose-agent-flow",
        "编排 Agent 流程",
        "已生成 Planner → Generator → Evaluator → Approver 工作流。",
      ),
      operation(
        "run-safety-check",
        "运行安全审计",
        "已完成提示词注入、数据脱敏和权限越界检查。",
      ),
    ],
    statusTracks: [
      "模型接入",
      "网关路由",
      "接口管理",
      "数据库管理",
      "可视化面板",
      "知识索引",
      "工具注册",
      "Agent 编排",
      "安全审计",
      "成本治理",
    ],
  },
  settings_center: {
    moduleId: "settings_center",
    title: "平台设置与治理控制台",
    subtitle:
      "租户、模块开关、用户角色、权限策略、模型路由、存储适配器和审计策略。",
    features: [
      feature(
        "tenant",
        "租户设置",
        "组织、项目、空间、法域、默认标准和数据隔离。",
        "平台管理员",
        "ready",
        ["租户 3 个", "项目 12 个", "法域 4 类"],
      ),
      feature(
        "module-switch",
        "模块开关",
        "14 模块启停、灰度、权限和 SLA。",
        "产品管理员",
        "running",
        ["启用 14 个", "灰度 2 个", "阻断 0 个"],
      ),
      feature(
        "roles",
        "用户角色",
        "业主、设计、造价、采购、工厂、监理、管理员等角色。",
        "IAM 管理员",
        "ready",
        ["角色 18 个", "用户 126 个", "冲突 2 个"],
      ),
      feature(
        "policy",
        "权限策略",
        "RBAC/ABAC、审批流、数据域和最小权限策略。",
        "安全管理员",
        "review",
        ["策略 42 条", "模拟 96%", "高危 1 条"],
      ),
      feature(
        "model-router",
        "模型路由",
        "OpenRouter、InferenceRouter、本地模型和成本策略。",
        "AI 平台工程师",
        "running",
        ["路由 8 条", "fallback 2 条", "成本 -12%"],
      ),
      feature(
        "storage-adapter",
        "存储适配器",
        "对象存储、CDE、模型仓库、档案库和缓存策略。",
        "平台工程师",
        "ready",
        ["适配器 5 个", "健康 100%", "延迟 42ms"],
      ),
      feature(
        "audit-policy",
        "审计策略",
        "操作审计、证据链、签章、保留期限和导出规则。",
        "合规负责人",
        "running",
        ["事件 12k", "保留 7 年", "导出 4 次"],
      ),
    ],
    operations: [
      operation("update-config", "更新配置", "已生成配置变更草案和回滚点。"),
      operation(
        "simulate-permission",
        "模拟权限",
        "已模拟角色权限、数据域和审批路径。",
      ),
      operation(
        "generate-settings-snapshot",
        "生成设置快照",
        "已生成平台设置快照和审计摘要。",
      ),
    ],
    statusTracks: ["租户", "权限", "模型路由", "存储", "审计"],
  },
};

export function getModuleOperationalProfile(
  moduleId: ModuleId,
): ModuleOperationalProfile {
  const profile = moduleOperationalProfiles[moduleId];

  if (profile) {
    return profile;
  }

  const fallbackTitleMap: Partial<Record<ModuleId, string>> = {
    planning_management: "计划管理",
    finance_hr: "财务人力",
    ai_center: "AI中心",
  };

  const title = fallbackTitleMap[moduleId] ?? moduleId;

  return {
    moduleId,
    title,
    subtitle: `${title} · 企业级生产文件与业务对象工作台`,
    statusTracks: [
      "业务对象",
      "输入资料",
      "过程文件",
      "交付物",
      "审批记录",
      "审计归档",
    ],
    features: [
      {
        id: "workspace",
        title: "工作区根",
        description:
          "模块默认工作区，用于承载业务对象、输入资料、过程文件、交付物、审批记录和审计归档。",
        status: "ready",
        owner: title,
        metrics: ["工作区已初始化", "文件系统已挂载", "审计链已启用"],
      },
      {
        id: "business-objects",
        title: "业务对象",
        description: "模块核心业务对象与 OpenConstructionERP 生产数据映射。",
        status: "running",
        owner: "业务负责人",
        metrics: ["对象状态可追踪", "支持审批流转", "支持证据绑定"],
      },
      {
        id: "deliverables",
        title: "交付物",
        description: "模块输出的 Token、报告、模型、清单、审批记录和归档资料。",
        status: "review",
        owner: "交付负责人",
        metrics: ["交付物可归档", "版本可追溯", "支持下游模块消费"],
      },
    ],
    operations: [
      {
        id: "generate",
        label: "生成业务凭证",
        result: "已生成模块业务 Token",
      },
      {
        id: "approval",
        label: "提交审批",
        result: "已进入审批流程",
      },
      {
        id: "archive",
        label: "归档交付物",
        result: "已写入数字档案",
      },
    ],
  };
}
